### ISSUE TITLE
"Water" in Hot Water isn't capitalized.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1009]
#861 was not fixed.

**Comment by UnlimatedStone9** [comment]
![image](https://user-images.githubusercontent.com/40124890/79588667-2b845d00-80cc-11ea-8c79-5a526ef3ddb3.png)

**Comment by alcatrazEscapee** [comment]
Since no version provided going to assume latest. As of which:

<https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/30b05fe351a82d2c7493a1436dd16df5b585453e/src/main/resources/assets/tfc/lang/en_us.lang#L795>

and as of now:

<https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/2e46bb3bd82abb122f14afb4eea46eb569b9cc79/src/main/resources/assets/tfc/lang/en_us.lang#L834>

More info or nope.
