### ISSUE TITLE
Naming of Animal Meats inconsistant

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1015]
**Describe the request**
Some animal meats have the word Meat at the end, but most dont
1. What problem or issue would this enhancement solve?
consistent naming scheme

**Meta Info**
 - TFC Version: 0.X.X.XX (at time of request)
.129

**Comment by aliceingame** [comment]
Blame the English language and not TFC. The game is consistent in it's use of English language.
There is some animals that have a specific name for their meat, such as beef or pork that are the easy word everybody know. These specific words mostly exist for the meat that are commonly eaten, there might be words for more, but most likely not well known.
For animals that have their "meat name", you do not use the word "meat", for example "beef meat" makes no sense.

So if you want to make it so all meat have "meat", you would have to call it "cow meat" or "bull meat"... because technically English language does have different words for each gender and even for baby (calf)... but in the case of calf, their meat would be veal, not beef.
So you cannot really change them all to "xxx meat".

Could you change them all to not have meat it the name ? Maybe ? Just tell me what is the proper name in English for "Bear meat" and I'll even sen the correction myself. Thing is, there is not a "meat name" for all animals.

**Comment by Azaysol** [comment]
well figured that might be the case. but thought that calling it Raw Bear/Cooked Bear would be enough

**Comment by Azaysol** [comment]
closing this, since it fits the intended naming scheme
