### ISSUE TITLE
TFCT: allowing right click to place pottery after first 'v' should be configurable

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1029]
Players got confused because 'v' is required to start a pit-kiln, but shift-right click works after the first item is placed. Should be a config option to disallow this additional method of adding pottery.

**Meta Info**
 - TFC Version: build 129

**Comment by alcatrazEscapee** [comment]
I think this is basically due to not knowing how the mechanic works:
 - Placed items use "V".
 - IF you want, you can also shift click into an existing placed item, as a convenience feature.

And if you are confused by that, then simple don't use one or the other. I see no good reason to add a configuration option to disable what is a QoL feature with no side effects whatsoever.
