### ISSUE TITLE
TFCT: Smoking and drying should be added

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1033]
Especially when playing 30 day months, more content options to preserve food will be appreciated.

While tastes are thankfully gone, "smoked pork" would be enjoyed.

 - TFC Version: build 129

**Comment by Claycorp** [comment]
Adding to this, Cheese is currently can't be preserved in any other way than sticking it in a pot. Smoking would provide a way to do this.

Plus these are fairly early on system, would be good for people starting out to have instead of relying on just pots. Drying/Smoked foods could use a smaller buff or the harder options can last longer.

**Comment by drhaber** [comment]
To add to this, the same device could be used for these too buffs. Drying is just the device placed in the world and smoking is the same device placed onto a fire pit (akin to how pots and Grills are placed on fire pits)

**Comment by weiplume** [comment]
Hello everyone. sorry for my English. How can I set the length of the month?

**Comment by Gaelmare** [comment]
> Hello everyone. sorry for my English. How can I set the length of the month?

This isn't the right place to ask this question. GitHub issues are not where we do support. I expect you just asked this question in Discord. Discord is better for this.

**Comment by alcatrazEscapee** [comment]
Going forward, this sort of suggestion should be in discord, not as an issue.
