### ISSUE TITLE
Putting too much ingredient in barrel recipe void extra

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#1041]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Extra items to be returned, the same way as you can make more than 1 stack of mortar in a barrel. I would expect extra to be dispensed in the output slot after taking the initial item, or just to put a message "too much raw ingredient".
2. What actually happened instead (i.e. what was the bug)
Tried to process 64 jute into jute fiber, but a full barrel can only process 50, so in the result, there was only 50 fiber and the extra 14 jute was voided.

**Meta Info**
 - TFC Version: 0.X.X.131

**Comment by Gaelmare** [comment]
This is by design. While the extra output ingredients can stack up like mortar, the input ingredients must be balanced to the liquid. There's no way to save the extra input ingredients.

**Comment by alcatrazEscapee** [comment]
The fundamental problem is that there's one input slot, and yes, it's possible for it to overflow, or be replaced (this also applies to fluids). However, we have a pretty strict policy: excess items or fluids are voided. It makes no sense (in the fluid case) to keep a backup, nor does it makes sense that excess items would be kept. What *could* be done, is make the recipe require an exact amount (i.e. not void excess by just not completing the recipe, but that restricts the recipe to only operating on exact ratios (because otherwise, one ingredient, either item or fluid, becomes the "exact ratio" ingredient and excess gets voided / stops recipe completion).

In this case, the input can be calculated beforehand. There's no excuse for putting a bad ratio in and getting a less efficient conversion, either items or fluids.
