### ISSUE TITLE
Prospecting Pick Yields Incorrect Results for Garnierite

### ISSUE THREAD

**Issue by tst5000** [TerraFirmaCraft/TerraFirmaCraft#1048]
**Describe the bug**
1. I expected the prospector's pick to say "Found a very large sample of/Found Garnierite
2. The text above the hotbar simply says "Found a very large sample of" or "Found"

**To Reproduce**
1. Use a prospecting pick near garnierite or on garnierite
2. ???
3. Profit

**Meta Info**
 - TFC Version: 1.12-1.0.5.132

**Comment by tst5000** [comment]
Update: happens with ANY ore

**Comment by Gaelmare** [comment]
Are you in an old world?

**Comment by tst5000** [comment]
If you mean old world by one created before .132, then yes. I believe I made my world in .126.

**Comment by Gaelmare** [comment]
There were significant updates to worldgen. You will need a new world. Not sure about the propick issue, but any new chunks will be wildly different.

**Comment by Gaelmare** [comment]
What is your language set to?

**Comment by tst5000** [comment]
English, I assume.

**Comment by tst5000** [comment]
I assume this has something to do with this commit: https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/44067135294b5c64f72e3b480778ad422195be1f

**Comment by aliceingame** [comment]
Someone said that yesterday on Discord, I tested ans it was working as intended. Other people pointed out that it does not work with Sponge (or at least not in all versions) or similar script tools.
Is TFC the only thing you have installed ?

**Comment by DisasterMoo** [comment]
> I assume this has something to do with this commit: 4406713

Yes, localization was changed to allow translation and also different translate options, ie: `Gabbro Garnierite has been found` instead of `Found Gabbro Garnierite`.

Your problem certainly is something else, because we already use the same translation method in other things like those two: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3f758c6cdf7efe4f117021ca72fc5475a5cc0cca/src/main/resources/assets/tfc/lang/en_us.lang#L2821
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3f758c6cdf7efe4f117021ca72fc5475a5cc0cca/src/main/resources/assets/tfc/lang/en_us.lang#L34

**Comment by DisasterMoo** [comment]
Seems the bug is actually a translation needing update, not a code bug
