### ISSUE TITLE
Predator mobs are defeated with boats.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1051]
TFC 132

With the new change to mobs that are only hostile during specific times you can just slap a boat down and they will end up inside of it making them harmless.

Either they should be prevented to get in the boat or should get out when hostile.

**Comment by DisasterMoo** [comment]
Found out what is causing this, and again #BlameMojang

It's not the creature that seeks a boat and then ride it. It's in the boat code that forces any non water entity or player inside of it (class `EntityBoat:L378`) in `onUpdate()` every tick.

Forge added `EntityMountEvent` to do things when an entity mounts another, but can't be used because if you cancel, the next tick redo the entire thing quickly causing a stack overflow crash.

Since we have our own boats I can override this behavior in it and fix, but if someone adds recipes to vanilla's boats back this issue would happen there. So, this will be a tape fix, not a bad one but still not the best solution.
