### ISSUE TITLE
Add larger smoke particles to firepit similar to vanilla 1.14 firepits.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1070]
TFC 133
This would be helpful for finding houses while the firepit is running and gives a benefit for keeping the firepit running when away.

**Comment by gospodin55** [comment]
how about just use 1.14 vanilla model?

**Comment by alcatrazEscapee** [comment]
A couple reasons I'd see:
 - Our fire pit model (imo) is better than the 1.14 model, and allows for placing a grill and soup pot.
 - It doesn't make sense from a development perspective to replace the vanilla fire pit as we do a *lot* more with ours. So from that point of view there's no reason not to have a separate model as two identical looking firepits that do totally different things would be confusing.
 - And last of all, because both of those are 1.14 things that we'd have to back port to 1.12 if attempted. No reason to change when we have a perfectly good model.

As for the smoke particles, the back-porting still applies, although it would be nice considering we're effectively replacing that functionality (in 1.14)
