### ISSUE TITLE
TFCT: Hot/spring water cannot be directly picked up in barrel

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1079]
This impacts dye and olive processing because to get this water into a barrel, need to bucket it.

To fix: allow barrels to be filled from finite water sources?

 - TFC Version: build 133

**Comment by alcatrazEscapee** [comment]
One thing to note: when you right click a barrel on an infinite fluid source, it fills the whole barrel, meaning it fills 10 buckets worth. Allowing this to be filled on finite sources would result in very easy fluid duplication - this needs to be taken into account.

**Comment by Gaelmare** [comment]
Thanks. So would allow fluid duplication with a red steel bucket? Mostly a
concern about addons and other mods then?

**Comment by Claycorp** [comment]
Just adding info from the conversation in the dev room on discord:

If this was to be added it would only pick up one block at a time. This makes it incredibly inefficient at actually filling the barrel because you would need to break and place the barrel for every source. While people would quickly realize how slow it is, they would quickly opt for using the wood bucket.

As for using spring water in recipes, yes it would be slightly more tedious to use but there isn't a shortage of the liquid in a single spring to call for duplicating the fluid.


I think it's fine as is, people just need to learn the difference between finite and infinite liquids. Though adding the ability for it to pick it up one at a time wouldn't be the worst thing, just not really helpful.

**Comment by alcatrazEscapee** [comment]
See #1085 for any further updates.
