### ISSUE TITLE
Cooking can be MUCH more grindy than in Classic

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1088]
In Classic, the player could stick a whole 160 oz stack ~= 64 item stack of meat in a firepit and cook to rare in 36 seconds with two clicks.
Cooking that stack of items in TNG takes 640 seconds if the user manages the cooking perfectly with much more attention needed.
Even if the user has a grill, the TNG cooking takes a minimum of 128 seconds with more than 128 clicks.
This also uses more fuel.

Ideas to fix:
Input stack slot that feeds into actual heating slot. Change gui to input heating slot in the fire.
Open to other ideas!

 - TFC Version: build 133

**Comment by Azaysol** [comment]
this would be a welcomed QoL change to cooking, while still having down sides if left un-attended for too long since the meat would burn

**Comment by DisasterMoo** [comment]
I don't see this being a concern. Compared to classic yes TNG is more grindier, that is simply because we changed how food is managed to be more like vanilla. Now, in vanilla, you cook 8 pieces of food / charcoal, 6 per log if you use planks. TNG looks more similar to this production than classic, and imo is fine as is (if #1065 is done, alleviating user input)

**Comment by alcatrazEscapee** [comment]
More things to be considered:
 - #1065 is QoL feature that should alleviate some of the difficulty.
 - imo the classic way of handling food didn't make much sense - huge stacks and small stacks *should* be treated differently.
 - Fire pit cooking is intentionally grindy (to a point) - It encourages use of either the charcoal forge (if you have an abundance of food and need to cook it all, and aren't bothered by the reduced expiration date), or the grill (the top tier cooking device).
 - Also, any measurement of time fails to mention that, as with a lot of repetitive tasks, *you can do these in parallel*. Having two fire pits effectively halves the time required.

**Comment by Kalzeroth** [comment]
*cough crucible has 9 slots cough*

**Comment by alcatrazEscapee** [comment]
In light of the large pile of advice / possible ways to make food less grindy, this seems like more of a behavioral issue and less of a mechanical one, and the proposed solution doesn't really solve the issues in a satisfying way. If there's more open ended brainstorming to be done rather than a specific concrete suggestion it should probably be done in discord first.
