### ISSUE TITLE
Apparently Tool racks can eat items on servers...?

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1103]
TFC 133

This is more of a note to investigate than anything else. It's been brought up by multiple people but never properly reported. Needs investigation.

**Comment by Rodhin** [comment]
**Summary:**
There are some sync issues with the tool rack.

**Steps to reproduce:**
There are some tools on the toolrack. Player one gets one of the tools, player two still sees the tool as attached to the toolrack. Player two can get the tool from the tool rack, it will appear in the player's inventory. When player two tries to use or move the item in the inventory (or only click on it) it will disappear from the inventory. The original item will be present at player one's inventory and will be usable without a problem.

**Expected results:**
The item shoul disappear from the toolrack for all the players.

**Actual results:**
The item won't disappear from the toolrack for other players.

**More info:**
We are a 5 people group playing in SMP, the sync issue is there for everyone. The issue was there before we added any other mods/addons to the server.

TFC version: 133
Forge server version: 14.23.5.2847
Forge client version: 14.23.5.2838
Additional mods: JEI, JourneyMap, WaterFlasks (TFC Addon), BetterFPS (only on client side)



I hope this could count as a proper report. If you need more info, maybe logs then just let me know!

**Comment by alcatrazEscapee** [comment]
Fair warning: I haven't been able to reproduce this, but I have changed the exact same code that was leading to desyncs with metal sheets for tool racks, so in theory this is fixed. If not it can be re-evaluated.
