### ISSUE TITLE
Compatibility with No Lava Bucketing

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1120]
**Describe the request**
Allow preventing using TFC buckets to pick up specific fluids using the No Lava Bucketing mod, this used to work by default, but some unforeseen change broke compatibility.
No I don't want to prevent a fluid going into the container completely, just manually in world.

**Meta Info**
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Compatibility with this mod: https://www.curseforge.com/minecraft/mc-mods/no-lava-bucketing

**Comment by alcatrazEscapee** [comment]
It seems that all they do is intercept `FillBucketEvent`, which I *believe* we fire on pickup, but evidently we need to verify.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.

The mod compat in question is 1.12 only, from what I can see, and this functionality (whitelisting buckets) should be doable with a tag in 1.18.
