### ISSUE TITLE
Skills should be harder to max

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1143]
We should treat skill increases a bit like xp levels, exponentially increasing the amount of effort it takes to max each level. Not make it too crazy, but should be harder to get to master. Smithing is the only skill I've not seen mastered within the first in-game year.

**Comment by DisasterMoo** [comment]
I agree, and if this is done, maybe add more bonus effects rewarding more those who specializes in something? (assuming it will be even harder to specialize)

My suggestions:
Prospecting: Increase range and/or at max level give hints on the general direction.
General Smithing: Make the green spot in anvils a bar which would grow in size by level (easier to smith), the other bonus, efficiency and durability is already good enough for even if we make smithing harder to level up.
Agriculture: Bonus crop growth speed and/or if the A, B and C nutrient comes back, ability to use fertilizer to supply missing nutrient.
The only skill that imo should be nerfed is butchering, seems to be giving too much food on high level.

**Comment by alcatrazEscapee** [comment]
Two things have been changed:
 - skills are slower to max in general
 - skills are exponentially slower on higher tiers to max.

I'm going to put a very hard stance for "no more skill bonuses / changes outside balance" because skills as a concept should go die in a fire, not be expanded.

Feedback welcome to see if this is too much, too little, etc.

**Comment by alcatrazEscapee** [comment]
This seems to be in a much better place:
 - skills are still much easier to obtain early levels, but very harsh to obtain later ones. I think this is fine in most cases, as long as it starts to take effect before getting to master.
 - prospecting can be quite easy to max it if you "grind" it e.g. by exploring oceans or cliff faces. While this was not the intent of the skill, it would require significant rework now to change it and given the essentially zero bonus it gives the player, it's fine.
 - butchering has been expressed to still be too easy to max - this was additionally reworked to give less skill from smaller animals and should be more consistent overall. (e.g. It now takes 33 squid kills instead of 12 for level one butchering)
