### ISSUE TITLE
Adding one tree or two trees for decorative OR Compat between BOP and TFC 

### ISSUE THREAD

**Issue by Xelbayria** [TerraFirmaCraft/TerraFirmaCraft#1149]
I'll keep it simple for now. I would like to see if it's possible for developers to just add one tree or 2 trees to TFC: 
-Cherry Blossom Grove or Pink Cherry Tree (it look like a pink cherry tree and it blossomed at springtime) 
-White Cherry Tree

BOP has these 2 trees which are why I want to use BOP and TFC to have fun. These trees are quite useful for decorative and if you get to see those trees in your backyard, it can be quite beautiful, especially with shader enabled. The problem is Compatibility between TFC TNG and BOP is not developed yet. So I am aware that it may be not possible to add compatibility between BOP and TFC because of generation and it would be too much work. 

Adding 2 trees to TFC may be better to do than trying to develop compatibility between two mods. I hope it's not much work to do. Please let me know what you think of this suggestion? 

**Meta Info**
 - TFC Version: As of today, using the latest version of TFC: TNG
 - BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar (RELEASE) OR  
    BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar (BETA) 
 - Using the latest forge version as of today.

**Comment by alcatrazEscapee** [comment]
If you want these trees, we have a very simple API for adding external trees to TFC. See [Tree](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.12.x/src/main/java/net/dries007/tfc/api/types/Tree.java). As such, there is no need for this to be added in base TFC.

We are not going to add explicit compatibility with BOP, it is basically impossible due to the differences in world generation given that TFC does not use biomes, and BOP is a mod that primarily adds biomes.

**Comment by Xelbayria** [comment]
@alcatrazEscapee 
Thank you for replying. Yes, I knew that it's not possible to add compatibility with BOP. your answer is what I just expected as it is. I'll have to look at Tree Link to see how it works. 

EDIT: I forgot to ask is there more information on Tree.java? or instruction so I can understand how it works?
