### ISSUE TITLE
Snow Textures missing TerraFirmaCraft-MC1.12.2-1.0.8.136 forge-1.12.2-14.23.5.2846-liteloader

### ISSUE THREAD

**Issue by velocityraptor-real** [TerraFirmaCraft/TerraFirmaCraft#1151]
Bug Description:
Snow textures are just missing. There is nothing more to tell

1. What did you expect to happen?
A snowy landscape in the winter
2. What actually happened instead (i.e. what was the bug)
Snow has no textures
4. If they would help to explain the issue, include screenshots
![grafik](https://user-images.githubusercontent.com/56190563/80860986-dddf2700-8c6b-11ea-9e8b-4ba432f94c60.png)

To Reproduce
1. Let it snow in the winter
2. Observe

Meta Info
 - TFC Version: MC1.12.2-1.0.8.136
 - Other mods: voxelmap.litemod, OptifineHD_U_F5, Damadgeindicators
 - None of these mods are probably needed to reproduce the bug.

**Comment by DisasterMoo** [comment]
1st: Try without liteloader
2nd: Try without optifine
If either one of those 2 are the culprit, there's no way to fix in our end. Both have closed source, which leaves us without a clue on how to determine the cause and fix

**Comment by alcatrazEscapee** [comment]
In addition:
 - are there missing model or texture errors in the log? Maybe check those to see if vanilla simply can't find an asset.
 - AFAIK liteloader is known to have issues with registry replacement (which this is), however I've not seen any specific issues with missing textures.

Otherwise, I (somewhat obviously) can't reproduce, so unless somebody can inform us what's going on here, this is going to be a nope.

**Comment by velocityraptor-real** [comment]
It works without liteloader
