### ISSUE TITLE
So I was eating some wheat grain and my grain nutrition went down, I also ate maize and it still went down. I tested it with before and after and sure enough it went down.

### ISSUE THREAD

**Issue by Dylan132004** [TerraFirmaCraft/TerraFirmaCraft#1152]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by Claycorp** [comment]
This is intended. You don't get nutrition points for eating raw/unrefined/unfinished grains. You need to make bread if you want the nutrition from it. Otherwise it's only for feeding yourself in dire situations when there is nothing else avaible.

**Comment by alcatrazEscapee** [comment]
There are two things going on here:

 - Firstly, as clay said, you don't receive nutrition for eating raw grains. The reason being that it incentivises the usage of bread and/or sandwiches.
 - Secondly, this is on-par with the new nutrition system. It is not a resource like hunger or thirst which decays periodically, and you need to eat to replenish it. It is based on the average nutrition of the last ~20 foods you ate. What this means, is that you can eat food, which restores nutrition, and your overall nutrition went down because it was less nutritious than your previous diet. In which case this behavior is completely expected.
