### ISSUE TITLE
Nether Portal use gives 'Internal Server Error' and disconnection

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1169]
Using a Nether Portal causes disconnection from multiplayer server with 'Internal Server Error' message.

**Meta Info**
 - TFC Version: 0.X.X.138 on test server

**Comment by Rongmario** [comment]
Yes, it seems to be crashing on Listener already listening: https://pastebin.com/Rd9Embvx

**Comment by alcatrazEscapee** [comment]
This can be resolved by removing the listener addition here,

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/6f71239c8126149f25acf9457203874db70b6adc/src/main/java/net/dries007/tfc/CommonEventHandler.java#L555

or by adding a `try catch` and just ignoring the error here,
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/6f71239c8126149f25acf9457203874db70b6adc/src/main/java/net/dries007/tfc/objects/container/CapabilityContainerListener.java#L70

However, both of these are probably related to #667, and this should be fixed with that as we need to track enough player data across dimension changes but apparently our sync capabilities are duplicating themselves.
