### ISSUE TITLE
Ceramic uncrafting recipes aren't lossless/can duplicate clay.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1213]
**Describe the bug**
1. What did you expect to happen?
To craft 5 clay from a ceramic item that is worth five clay.
To not craft a single ingot mold into 3 clay allowing users to make 2 molds for 5 clay and craft it into 6 clay...
I propose making the recipes actually all output 5 clay, what went into it, and have the clay uncrafting recipe have either 1 mold = 2 clay (loosing one in the process), or 2 molds shapeless recipe = five clay, or both if you like.
![image](https://user-images.githubusercontent.com/40124890/81310678-52ef9980-907c-11ea-9e49-6c9ada6c9f23.png)
![image](https://user-images.githubusercontent.com/40124890/81310757-6f8bd180-907c-11ea-931b-3c2ec72b9c9d.png)
![image](https://user-images.githubusercontent.com/40124890/81310832-86cabf00-907c-11ea-940d-c7dcb2269cc7.png)

**Comment by eerussianguy** [comment]
Could probably just get away with reducing the mold output to 2 clays

**Comment by UnlimatedStone9** [comment]
That would work. I just wonder why you can't mush clay back into the right amount.

**Comment by Claycorp** [comment]
I made these. (big surprise there)
Idea behind it all was you are going to lose some clay from making it. Plus if you managed to get this far and don't want it anymore it was better than just tossing it like you would have. Clay is super common and this was just thought of as a way to recycle mistakes/surplus back into the stack essentially.

The ingot mold issue was due to copy paste. 

I don't care either way what it gives back. If people really want them to return the full amount that's fine, it can be changed.
