### ISSUE TITLE
Time passing too fast

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1222]
So when i logged off yesterday it was October 1011, when i came back today a month had passed (November 1st 1011) but all the animals i had pregnant gave birth, all my baby animals became adults, most of my adult animals became old. I wasnt expecting to see this much change so im guessing this was because of the update.

**Meta Info**
 - TFC Version: 1.0.12.141

**Comment by DisasterMoo** [comment]
There wasn't any calendar changes, the time passing is the same. What changed is how long animals  take to give birth, become adults and grow old. 

To put simply, we used a number of days similar to how long it takes in real life for all animals, now we are using a factor of months, ie: cows took 1080 days to become adults, now it takes 36 months, which mean you can make them grow faster by setting the month length lower.

Lastly, animals loaded from the prior build probably will become old instantly, since the conversion from 30 days -> 8 don't change their birth day, just the number of days required for aging.

**Comment by nuuno2000** [comment]
Ah I get it! And yes all baby animals became adults instantly and all adult animals became old instantly, but that doesnt apply to animals i had at my base only, because i went exploring new chuncks and all the animals i found were also old (im guessing all chunks in the map have been pre loaded). This is only a problem because the update happened in a map from a previous version though right? In a new map created in 141 the animal growth and aging should feel normal right?
Also, this might be a problem in the test server since basically all animals are old and unbreedable now.

**Comment by DisasterMoo** [comment]
Yes to all these questions, and yes, test server pre-loaded animals surely will be old too. If you want to use an old map for a while yet I recommend disabling the old aging in the config until you get yourself a bunch of new animals. We are still figuring out balancing issues to make TFC even better. Hopefully, there will be no more time discrepancies from old saves after this.
