### ISSUE TITLE
Fertilized eggs don't display fertilized tooltip

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1234]
Title

**Meta Info**
 - TFC Version: 1.0.12.141

**Comment by DisasterMoo** [comment]
More info please.
- Eggs hatch but they don't display "Fertilized"?
- Are you playing on a server or SSP?
- Are there any other mods? (don't need to list all but ones that can and would override tooltips somehow, ie: Hwyla or TOP?)

**Comment by nuuno2000** [comment]
The eggs hatch but neither the eggs nor the duck display "fertilized"
Im playing on the test server
ive got Hwyla instaled

**Comment by nuuno2000** [comment]
I would also like to know if the rake keep fertilizing the eggs forever and i need to take him away or it dtop after a set amount of eggs

**Comment by DisasterMoo** [comment]
Moving out to this issue since it matters here.

Clearly, there's something wrong in another place. I'm getting the tooltip since the start of egg hatching mechanics:
![image](https://user-images.githubusercontent.com/22617477/81961992-7c16a980-95e9-11ea-830b-cce5214c1120.png)
(screenshot taken in build 142)

Can you check if you have other capabilities tooltip? (heating, food nutrition, decay and other things).

**Comment by nuuno2000** [comment]
So i fertilized all of my ducks (well, the drakes did) and waited for them to lay eggs (slept but i doubt that makes a difference) and this is what i got 
![2020-05-15_03 32 16](https://user-images.githubusercontent.com/64791157/82005245-c5eca780-965c-11ea-940d-dce3ffc30aa8.png)
So no, im not getting any other tooltips on eggs even though im getting it on other items
![2020-05-15_03 34 08](https://user-images.githubusercontent.com/64791157/82005347-09dfac80-965d-11ea-8377-6527f258a13c.png)
(some grain as an example)
Even though the eggs dont display any tooltips they seem to be working as you can see from the baby ducks in the 1st screenshot
All screenshots taken in build 142
