### ISSUE TITLE
Mule's health bar shows 0/0

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1273]
Mule's health bar shows 0/0
Possibly all horse type offspring but only raised mule so far.

**Meta Info**
 - TFC Version: 0.X.X.142 on test server

![zero](https://user-images.githubusercontent.com/58256171/81963176-a88fed00-960c-11ea-83d3-989b0457774b.png)

**Comment by DisasterMoo** [comment]
Can't reproduce. It  may be a desync issue, or either something from old worlds.

Also, while checking for this, i found that currently you can't breed mules because donkeys and horses don't seek each other when in love, which i already fixed in a PR, so hold your horses (pun intended) to test in a new world after next build.

**Comment by p0kes** [comment]
Mules from previous versions. I'll close this now and re-open if needed once I find some updated version equines.
