### ISSUE TITLE
Some sandwiches are preserved inside small vessels while others are not.

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1282]
I've only noticed this with sandwiches, not sure if it happens with other food
![2020-05-16_21 43 33](https://user-images.githubusercontent.com/64791157/82151509-b4212500-9853-11ea-82fb-a14d4ef14e37.png)
![2020-05-16_21 43 35](https://user-images.githubusercontent.com/64791157/82151512-b6837f00-9853-11ea-88de-e21a2c7b2805.png)

**Meta Info**
 - TFC Version: 0.X.X.142

**Comment by Gaelmare** [comment]
please retest this and give more exact reproduction steps, if possible

**Comment by nuuno2000** [comment]
Ive been able to reproduce it in 149, all i did was make the sandwiches are normal and then put them in the vessel.
Edit: If i move them it gets fixed

**Comment by alcatrazEscapee** [comment]
> and then put them in the vessel.

This is the key part. I have been completely unable to figure out what the insertion method is which breaks our listeners. I know this has come up in the past (specifically with swapping slots via number keys), which we have since fixed. So if there's a method to bypass that, it would help to know exactly what said method is, i.e. exact click steps.

> Edit: If i move them it gets fixed

Yes, nothing is special about these sandwiches, it looks very much like you just managed to insert them in such a way which did not trigger our insert event listeners.

**Comment by nuuno2000** [comment]
I always shift click them into the vessels
