### ISSUE TITLE
Annoying "Punch A Tree" card won't go away

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1322]
**Describe the bug**
Collecting wood doesn't make the "Punch A Tree" tutorial flag go away

**To Reproduce**
1. Create a new world
2. Follow the tutorial at the top right of the screen
3. The tutorial, on top of being inaccurate, will not go away after successfully harvesting wood with an axe.

**Meta Info**
 - TFC Version: 1.2.1.144 (any version previous as well)
 - Latest forge (any version previous that works with TFC:TNG as well)
 - No mods necessary to reproduce bug

To fix, something like IKWID to skip the tutorial on world creation, or some oredictionary shenanigans.

**Comment by Gaelmare** [comment]
This is a vanilla issue that this mod cannot do anything about.

I recommend editing the "options.txt" file in the minecraft folder and updating
"tutorialStep:none"

**Comment by alcatrazEscapee** [comment]
> or some oredictionary shenanigans

AFAIK not possible because of how bloody hardcoded vanilla's toasts are.

Possible fixes for this:

 - Use a mod that does this, and gives you all forms of control over this: <https://www.curseforge.com/minecraft/mc-mods/toast-control>
 - In `options.txt` in your minecraft instance, set `tutorialStep:none` (this is the "standard" way to deal with this, even in vanilla)

If we were to add anything here, it would literally be copy paste of what toast control does just with less customization because it's really not our problem.

**Comment by ghost** [comment]
Ok, thanks for your replies
One possible hacky solution I thought of is to momentarily give the player a vanilla log on first joining the server.
The way I fixed it was with a simple /give, so possibly the toast is just waiting for the player to receive any vanilla log, not specifically for the player to actually break the log.

**Comment by alcatrazEscapee** [comment]
Given the availability of solutions and the fact we don't really care to copy paste toast control...
