### ISSUE TITLE
Mules spawning

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1323]
There lots of mules on the test server. Haven't seen any donkeys yet.

**Meta Info**
 - TFC Version: 0.X.X.145 on test server

**Comment by nuuno2000** [comment]
Imo mules shouldnt even spawn in the wild

**Comment by nuuno2000** [comment]
There might be a but making mules spawn rates way too high, but donkeys still spawn, ive just foud a few

**Comment by p0kes** [comment]
Mules shouldn't spawn in the wild (and certainly not in 'families'! ). They should be bred only.

**Comment by McGoogle3000** [comment]
You should get mules if you have Jacks and Mares in proximity

**Comment by DisasterMoo** [comment]
Hey guys, need help here to diagnose this. 

I've placed code hooks everywhere to determine if one spawned ie: their living update (this is called every tick), spawning, init AI, etc, and I generated a bunch of chunks while waiting for one of those hooks update and tell me one spawned. Then, the answer: Not a single one spawned in 100x100 chunks.

So I must ask:
- Are your worlds old (yes i don't know much about the test server)? There was a bug in earlier versions that mules used the donkeys' config to spawn.
- Are your configs default?
- Are there any other mods that spawn vanilla mules? Vanilla animals that have a counterpart in TFC are replaced, if enabled in config.

Lastly, if you guys have any way to reproduce this, please let me know (world saves are not helpful of course because they already spawned, i need to know the cause not the outcome).

**Comment by p0kes** [comment]
Just made five fresh worlds, default configs, TFC 146 the only mod, mules visible from spawn point every time.

**Comment by DisasterMoo** [comment]
Looks like it was old config playing tricks.
