### ISSUE TITLE
Bucket is consumed when making dough

### ISSUE THREAD

**Issue by boltonlass** [TerraFirmaCraft/TerraFirmaCraft#1328]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?  When making dough the bucket is emptied but retained.
2. What actually happened instead (i.e. what was the bug)  The bucket was lost.

Initially was playing on official server, but also happens in single player.

**To Reproduce**
Attention to detail is important!
Create flour, get bucket of water.  In inventory put bucket of water and flour together to get dough.  Then dough outputs but the bucket is lost.

**Meta Info**
 - TFC Version:  TerraFirmaCraft-MC1.12.2-1.3.0.145
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by McGoogle3000** [comment]
I had the same problem when turning cornmeal flour and rice flour into  dough the bucket of fresh water is consumed instead of still having the empty bucket.  I don't have any other grains to try.

First happened in:  TerraFirmaCraft-MC1.12.2-1.3.0.145
Updated to: TerraFirmaCraft-MC1.12.2-1.3.1.146 and still present

uninstalled all mods besides terrafirmacraft and same result
