### ISSUE TITLE
Olives should only be edible after being brined

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1364]
Olives are inedible straigh from the tree, brining makes them edible and should also make them last for much longer.
I would also suggest removing the hability to pickle/ preserve them in vinegar and substitute it with brining/preserving in brine only.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by alcatrazEscapee** [comment]
In order to do this, we would have to:
 - Special casing olives to be non-edible foods, but only when a certain trait is applied.
 - Special casing brining foods to not apply to olives.
 - Writing a separate brining recipe and trait which only applies to olives, and apply custom preservation effects.
 - Special casing pickling to not work with olives.

Pros: It's more realistic? I think?
Cons: It's a butt load of effort, hard coded exceptions, and inconsistencies for no real game play benefit.

I think the negatives outweigh the positives on this one.
