### ISSUE TITLE
Barrel makes vinegar directly from water and apples

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1386]
Placed approx 20 apples in a partly full barrel of water and sealed it (once only). Returned to find vinegar instead of cider.

**Meta Info**
 - TFC Version: 0.X.X.146 on test server

**Comment by DisasterMoo** [comment]
That is because cider is made in 8 in-game hours and then vinegar is started as soon as the cider recipe is done, taking another 8 in-game hours to make.

Conflict here is because vinegar is made from any fruit, and cider is made from a fruit (Apple).

Edit: We talked and this is intentional behavior. You can carefully check your ingredients and put the amount you want to get cider or you can unseal it after cider is done but before vinegar completes.
