### ISSUE TITLE
Making crucible alloying *slightly* easier to work with

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [TerraFirmaCraft/TerraFirmaCraft#1396]
**Describe the request**

I was watching the VOD for Pakratt's TFC Tuesday and the issue Meteor had with alloying made me wonder if there could be an "easier" way to handle alloys. Currently when you alloy in a crucible it stays in the mixed metal form until poured, which could be time consuming. I thought of two possible ways to improve this mechanic, each of which could be useful on their own but neither is mutually exclusive:

- When a crucible containing a mixture of metals cools completely, the contents solidifies into the alloy such that when reheated it is no longer considered a mixture. 
  - As a possible QoL improvement, if an alloy would create an "Unknown Alloy" when cooled it could retain the percentages of the metals while still in the crucible.
- Or, if you place a crucible on top of another crucible, placing a tuyere in the output slot would pour the alloy into the bottom crucible as the finished product.
  - Obviously, just as with the blast furnace, the tuyere would lose durability as the metal is poured through it.

**Meta Info**
 - TFC Version: **1.3.3.148**
 - Is this a compatibility feature for other mods? *No*. Or a enhancement for TFC alone? **Yes**
 - If necessary, what other mods (including versions) would this require? **None**

**Comment by DisasterMoo** [comment]
> When a crucible containing a mixture of metals cools completely, the contents solidifies into the alloy such that when reheated it is no longer considered a mixture.

*I can hear people crying from the distance...*

I disagree with this, there's possibility for addons and CT to register other metal mixtures which can use not the finished alloy product but the contents as well, ie: Brass (zinc + copper) and bismuth bronze (zinc + copper + bismuth), or finished products that could have a melting point higher than the contents (yes, this is possible, not that is it believable, but it's their pack and we have to consider this scenario). Not to mention hardcoded special casing we would need to accomplish this.

> Or, if you place a crucible on top of another crucible, placing a tuyere in the output slot would pour the alloy into the bottom crucible as the finished product.

That is more manageable, and why not? but first we have to address the issue of how to heat this second crucible.

Lastly, what is the issue here btw? You need to get ingots and melt it back for another alloy? (I can see that for Red/Blue steel).

**Comment by alcatrazEscapee** [comment]
The "issue" that was experienced, was someone trying to mix copper, silver, gold, steel, and nickel, and expecting it to make black steel.

What actually happened, because alloy recipes are not recursive (and we aren't going to make them that way, that would be problematic for a whole host of reasons, not to mention weird), it produces unknown alloy instead of (what one may assume to be the case) black steel.

**Comment by TenkenNoSoujiro** [comment]
I've considered a few other alternatives that are more "realistic":

- In a crucible containing a potential alloy in mixed form (1), place the crucible item that you want to contain the final alloy (2) in the output slot. The final alloy will pour into the crucible item (2):
  ![crucible1](https://user-images.githubusercontent.com/46035330/86274830-255c3380-bb87-11ea-90ce-f339891d02a7.png)
  - The crucible (1) can be heated to the correct temperature to reach the alloy's melting point as it is heated directly.

- Place a crucible item containing a potential alloy in mixed form (1) into an input slot of a crucible where you want the final alloy (2). The final alloy will pour into the the crucible (2):
  ![crucible2](https://user-images.githubusercontent.com/46035330/86275604-67d24000-bb88-11ea-96da-7f3f7139b6e2.png)
  - The crucible item (1) can be heated in the same way a vessel or ingot mold can be heated to reach the alloy's melting point.

Both of the above alternatives are based purely on the existing *pouring* concept employed by vessels/molds with respect to crucibles.

Another option might be the possibility of forging a [sprue](https://en.wikipedia.org/wiki/Sprue_(manufacturing)) to place in an output slot, and runners to connect two standing crucibles:

[![sprue](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Casting_gating_system.svg/800px-Casting_gating_system.svg.png)](https://en.wikipedia.org/wiki/File:Casting_gating_system.svg). 

A casting/gating system using a sprue and multiple runners could be an interesting addition for late game casting of multiple molds at once.

**Comment by alcatrazEscapee** [comment]
This is getting into "large new feature" territory, which is better suited to discussion in our discord #suggestions channel. The existing recipe checking functionality isn't going to get changed (crucible recipes are not going to be recursive). There is some merit to making crucibles able to pour into other crucibles, but that's also a very delicate subject at it involves building the fluid capability onto the item (something we've mainly avoided due to laziness). That would be useful but also involve a lot of rework about how we handle crucibles.

The result being the "issue" here isn't getting fixed, and this discussion about possible improvements to make this a nicer mechanic to work with can be moved to discord.
