### ISSUE TITLE
Server/Client ticking block crash upon bloomery breakage

### ISSUE THREAD

**Issue by don1819** [TerraFirmaCraft/TerraFirmaCraft#1416]
**Describe the bug**
Server crashed upon mining up the bloomery door. Seems to do it with any bloomery setup
Any amount of iron looks like all types, and if bloomery doors are open or closed. I tested it on my client and it happens as well
1. Wanted to break bloomery door with Pickaxe 
2. Client Crashed
3. https://pastebin.com/UktUSTHp

**To Reproduce**
1.Fill bloomery with charcoal, then with Iron of choice
2. Then Attempt to mine up bloomery door

**Meta Info**
 - TFC Version: 1.4.0.149
 - Pure TFC, No mods

**Comment by alcatrazEscapee** [comment]
I shall point out this is an excellent example of "upload the full log, not just the crashlog" As the crashlog points to:
```
    at net.dries007.tfc.objects.te.TEBloomery.func_73660_a(TEBloomery.java:127)
```
which *really hints* that this is an appearance of a known sponge issue (tile entity ticking air after block is gone).

However, it's actually caused by another issue (bloomery failing to drop all it's items after it's removed) which then crashes the next tick. This causing issue is spat out in the log and much more informative of the actual situation.
