### ISSUE TITLE
Remove the fact that refined wrought iron blooms >100% always melt down to 100%

### ISSUE THREAD

**Issue by ddemarco5** [TerraFirmaCraft/TerraFirmaCraft#1419]
I believe this is a misleading, unnecessary behavior.
Without some added distinction between the two sizes of wrought iron blooms, this loss mechanic can be unexpected and confusing.

I suggest removing this mechanic altogether, or adding some additional detail that might make this mechanic more expected.

For example, renaming refined iron blooms >100% "Unrefined Iron Bloom", or something similar.

**Comment by alcatrazEscapee** [comment]
No, this is a very intentional mechanic to prevent players from melting iron blooms post-bloomery into wrought iron. They instead need to be worked on an anvil. Wrought iron blooms < 100 can be melted, or used as bloomery fuel as they can't be worked.

For future, the plan is to make blooms melt into cast iron, which will solve this problem in a rather more intuitive way - by melting the bloom you are still wasting product as the key word in "Wrought Iron" is that it's *wrought*.

**Comment by DomDeMarc** [comment]
But when you melt a refined bloom = 100 you get the full amount. No loss, thereby removing the final step of hammering into bars... so the behavior is seemingly inconsistent.
Maybe it should be changed so that when you melt ANY bloom you lose a set percentage?

I like that pour into cast iron idea though, seems like a good way to go.
