### ISSUE TITLE
FishingMadeBetter mod dont work with tfc

### ISSUE THREAD

**Issue by Woody-0w0** [TerraFirmaCraft/TerraFirmaCraft#1429]
**Describe the bug**
Make sure to include:

I expect to add FishingMadeBetter mod.

but FishingMadeBetter mod dont work correctly with TFC : Reeling hud disapeared,fish bite but catch nothing,even change the config of FishingMadeBetter mod to make fish be caught immediately
no crash log

**To Reproduce**
Attention to detail is important!
1. Do 'add FishingMadeBetter mod to mod folder'
2. Then 'find FishingMadeBetter mod dont work correctly( Reeling hud disapeared, fish bite but catch nothing,even change the config of FishingMadeBetter mod to make fish be caught immediately )'
3. delete'tfc mod'
4. Then 'find FishingMadeBetter mod works'

**Meta Info**
 - TFC Version: 1.5.2.152
 - FishingMadeBetter Version: 1.12.2-1.1.3

anything changed in fishing？FishingMadeBetter mod dont work with tfc

how to make fish be caught immediately:
open \.minecraft\config\fishingmadebetter\fishdata\vanilla.json
change "minReelAmount"value: 0,and"maxReelAmount"value: 1

**Comment by Woody-0w0** [comment]
maybe TFC  could add a switch in config file, for player to choose vanilla fishing mode or tfc fishing mode

**Comment by Woody-0w0** [comment]
link for FishingMadeBetter mod
[https://minecraft.curseforge.com/projects/fishing-made-better](url)

**Comment by alcatrazEscapee** [comment]
TFC does not change anything about fishing.

> maybe TFC could add a switch in config file, for player to choose vanilla fishing mode or tfc fishing mode

This is irrelevant.

**Comment by Woody-0w0** [comment]
> TFC does not change anything about fishing.
> 
> > maybe TFC could add a switch in config file, for player to choose vanilla fishing mode or tfc fishing mode
> 
> This is irrelevant.

thanks！

**Comment by Azaysol** [comment]
believe you can use Just A Few Fish mod, think it works with TFC. just need to add a proper crafting recipe for the fishing pole

**Comment by Woody-0w0** [comment]
> believe you can use Just A Few Fish mod, think it works with TFC. just need to add a proper crafting recipe for the fishing pole
I had thought about it, but...
I feel something wrong with mob spawn of other mod.
Now, give it up and plan to change the fishing loot table .

**Comment by alcatrazEscapee** [comment]
Two things:
 - Fishing Made Better is closed source, All Rights Reserved, has no official issue tracker, and hasn't been updated in two years.
 - The most likely cause of this problem I can see would be some form of hardcoded water or biome check, which will obviously fail in TFC. This could probably be checked by seeing if the mod does work with TFC installed, but not in the TFC world type (vanilla water + biomes). If this is the case, then this is a request for the other mod to deal with. (although due to the above facts, good luck).

As I said, we don't change *anything* about fishing, and since I can't poke in their source to see what's going on, this isn't going to be fixed by us.
