### ISSUE TITLE
Jute net + Hot water barrel recipe should not try and ignore fluid ingredient - needs to be replaced with consuming fresh water

### ISSUE THREAD

**Issue by AnodeCathode** [TerraFirmaCraft/TerraFirmaCraft#1439]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? With one full hot water barrel, clean 1 dirty jute net and still have a full barrel of hot water.
2. What actually happened instead (i.e. what was the bug): I ended up with 125mB of Hot Water in the barrel

**To Reproduce**
Attention to detail is important!
1. Have a full barrel of Hot Water
2. Place one Dirty Jute Net in barrel item slot and seal.
3. Wait one hour.
4. Barrel will complete recipe in 1 game hour
5. Barrel will have 125mB of Hot Water in it and 1 Clean Jute Net

In TEBarrel.Update()

Where it has:

     if (recipe.isValidInput(inputFluid, inputStack))
                    {
                        tank.setFluid(recipe.getOutputFluid(inputFluid, inputStack));

It needs something like:
      

      FluidStack outputFluid = recipe.getOutputFluid(inputFluid, inputStack);
                        if (inputFluid == outputFluid){
                            int amount = inputFluid.amount + outputFluid.amount;
                            tank.setFluid(new FluidStack(outputFluid.getFluid(), amount));

                        } else
                        {
                            tank.setFluid(outputFluid);
                        }

Dunno, I'm no coder.

**Meta Info**
 - TFC Version: 152
 - Were any other mods included? Can you reproduce it without these other mods? Yes / Yes

**Comment by alcatrazEscapee** [comment]
So the issue at hand is that this recipe in question is not setup correctly. As is evident, a recipe which has equal input + output amounts does not equal "does not consume stuff" and should not be used that way (as it's rather counterproductive to the whole situation, since there's no real importance on the specific limit amount).

What *should* happen, is this recipe should be changed to consume fresh water (instead of spring water) at a reasonable rate per jute net.
