### ISSUE TITLE
Grain soup and Grain salad cannot be crafted

### ISSUE THREAD

**Issue by kwk1001** [TerraFirmaCraft/TerraFirmaCraft#1461]
**Describe the bug**
We found that :
When making grain soup and grain salad, any ingredient belonging to the grain categlory (including grain, flour, dough, bread and even sugarcane) cannot be put into the GUI, so that any grain soup or grain salad cannot be crafted.

**Meta Info**
- Version: TerraFirmaCraft MC1.12.2-1.5.3.153

**Comment by alcatrazEscapee** [comment]
The restriction on ingredients (which is simply an ore dictionary name tied to `categoryMeat`, `categoryFruit`, etc.) is intentional from a balance point of view. The choice of output item is purely dependent on the actual nutrient content of the ingredients. Thus while within TFC these may not be possible to be crafted, it's entirely possible that they could be made to be crafted, simply by adding foods with specific category and nutrient values.
