### ISSUE TITLE
Male Ducks are not fertilizing eggs

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1466]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? for familiarized male ducks to fertilized duck eggs
2. What actually happened instead (i.e. what was the bug) nothing

**Meta Info**
 - TFC Version: x.153

**Comment by DisasterMoo** [comment]
Ok, so, I wanna know, how are people testing it? Because in my tests they are working fine.

Here's how I do it:
- Spawn a drake and a duck
- Set familiarity to 0.3 for both
- Give them both food (in this case, i used Oat grain)
- You will see the love particles and they will try to mate
- The female tooltip shows that she is fertilized.
- The egg that came after that is fertilized, so it is working.

This process is exactly the same for chickens btw.

**Comment by Azaysol** [comment]
ahh, i was testing it differently like in old tfc. closing

**Comment by DisasterMoo** [comment]
So, basically, it is a discrepancy between classic TFC and our current method.

For future reference, I've done a bit of research and found out that our current method is true to reality, bird species mate by touching their cloacas.
