### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=can_fall...

### ISSUE THREAD

**Issue by AnodeCathode** [TerraFirmaCraft/TerraFirmaCraft#1477]
So I had an interesting couple of server crashes. First one was this one: 

[Crash1 ](https://pastebin.com/RH2LGJw8 )

where it's trying to get the can_fall property of a TFC block and fails. That crashed the server. Player at the time was breaking a block with an IE Drill. Clearly it triggered a collapse. But one of the blocks crashed the server. This was in the TFC standard overworld. No other modded blocks in the overworld.

 The server brought itself back up and then crashed again:

[Crash2](https://pastebin.com/fcafiNn6)

This one looks like it's trying to read the world tracker data but fails with an NPE and crashes again.
Pastebin
Crash 1 - Pastebin.com

Pastebin
Crash 2 - Pastebin.com

Full disclosure, in talking with the player who was breaking a block at the time, it was being done not with a TFC pick but with an Immersive Engineering Drill.
But the first one seems like some weird bug. The second seems like there should be something to catch the data being botched or garbled or non-existent.

TFC: terrafirmacraft-mc1.12.2-1.5.5.155

This was in a pack with lots of other mods, and it was a modded tool breaking the block.

**Comment by Therighthon** [comment]
I was the one breaking the blocks, not much to note. I was breaking a vertical 3x3 of blocks, made up of raw stone, coal ore, and cobble. The drill doesn't break all 9 blocks at once, I don't know if it breaks them in the same order every time, but I know blocks can become unsupported and start falling before the drill breaks them

**Comment by alcatrazEscapee** [comment]
So the first crash basically seems like something that we can't really fix, not without a solid reproduction case. IE isn't supporting 1.12 anymore (rightfully so) and so unless that becomes a persistent issue it ain't getting fixed.

However the second crash is actually an issue that hasn't been exposed yet because it hadn't been needed. Turns out, *any* collapses that were saved to NBT and reloaded would fail to reload. However since they generally happen very fast and as a result of player action, it hasn't been noticed until a crash forced the server to shutdown and serialize an attempted collapse. This has been fixed.
