### ISSUE TITLE
Config to disable/enable "Force doDaylightCycle to false as no players are logged in"

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1490]
All in a title. I'm testing on my private server changes to time of decay and year but with this being forced i cant do that without players on server every time. Will be good if there an option to disable or enable this feature.

**Comment by Azaysol** [comment]
while the config option would be nice, could you not use /timetfc add days/months for your testing purposes?

**Comment by ghost** [comment]
@Abdyman Yes i can, but i have some players on my server that plays normally, without using TFC commands. They dont play 24/7 so crops growth and time goes slowly. My testing purpose is to find best value for days per month if a server time will go endless, so that after a conditional real day all food does not rot and a whole year passes.

**Comment by ghost** [comment]
Also when i use this command (/timetfc add), crops sometimes not growing and stucking on one stage, so i dont use it when have players on a server.

**Comment by alcatrazEscapee** [comment]
This very much seems like you are trying to solve a problem the incorrect way. I *really* do not want to provide a config option for this for a number of reasons, unless it's actually necessary. So:

> when i use this command (/timetfc add), crops sometimes not growing and stucking on one stage

This is both misleading (because crops very much will time track internally, and will update on random ticks based on total time passed since the last tick), and incorrect (because as of cea1049105ae451314c81739782ace6ce9220f60 this update actually happens on any major time skip (e.g. via command) as well as on random ticks.)

And this reason

> I'm testing on my private server changes to time of decay and year

does *not* justify adding this as an option as has been explained, there are commands that let you explicitly control how these work, and immediate in-game feedback for any change you make.

So please explain *exactly* what your goal is, and we can try to point you towards existing ways to achieve this.

**Comment by ghost** [comment]
With cea1049 fix now it is not necessary. You can close this issue.
