### ISSUE TITLE
Sabertooths always neutral to a player.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1491]
Sabertooths do not attack player neither day nor night. They attack only if a player attacks first. If i'm not mistaken sabertooths should attack players on day as an opposite to panther that attacks on night.

Version: TerraFirmaCraft MC1.12.2-1.5.4.154

**Comment by alcatrazEscapee** [comment]
I'm very tempted to say this is actually just due to https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1480 and that the sabertooths you're seeing are just children, and hence not aggressive. (I'm not aware if they are meant to still be aggressive as children, @DisasterMoo can probably answer that.

**Comment by Azaysol** [comment]
Sabertooth attack at night, Lions are the only current Feline family that attack during the day. Will be changed to match other Felines in upcoming update

**Comment by DisasterMoo** [comment]
Second to Abdyman: yes, Sabertooth's AI works like the other predators and only attack durning the night while children won't do anything until provoked, most certainly it was related to #1480.
