### ISSUE TITLE
book crash

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#1498]
**Describe the bug**
minecraft crashed when opening the book page getting started.

**To Reproduce**
open the book page getting started.

**Meta Info**
 - TFC Version: 1.6.0.1
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
crash report : https://gist.github.com/Mrthomas20121/15423dae47d6165a10a84d1efd156016

**Comment by alcatrazEscapee** [comment]
Firstly, I can't reproduce at all just with TFC. Looking at the crash report:

```
Caused by: java.lang.NullPointerException: Unknown Heat recipe: tfc:glass
```

There's your problem. You removed a recipe that the book is using, without modifying said page of the book. The book has intentionally been made fail-fast: It will log an error on startup if a page fails to build correctly, and then later crash, rather than the developer have to track down issues as pages just display as blank.
