### ISSUE TITLE
Weirdness with eating a variety of food and maximum health.

### ISSUE THREAD

**Issue by staridiot** [TerraFirmaCraft/TerraFirmaCraft#1557]

**Comment by alcatrazEscapee** [comment]
Your current nutrition is effectively the *average* nutrition of the last 20 meals you've eaten. Eating raw ingredients (which have very little nutrition / item), means you will on average, have very low nutrition. Eating the same item over and over, you will see no change in your overall nutrition. Your nutrition and maximum health **do not decay passively**. They will only ever change when eating foods.

The best way to maximize your nutrition is to eat foods with a high total nutrition / food item. In order to gain maximum nutrition, you need to consume 1 of each nutrient per food item (drinking milk, and using a variety of soups and sandwiches is often the best way to do this). Eating raw ingredients is a very ineffective way of getting high nutrition since they tend to have very small amounts of nutrition per item.
