### ISSUE TITLE
Ingots shift clicked onto an anvil cannot be placed as ingot piles.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1586]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Nothing
2. What actually happened instead (i.e. what was the bug)
Ingots shift clicked onto an anvil cannot be placed back down into ingot piles.

**To Reproduce**
Self explanatory

**Meta Info**
 - TFC Version: 1.12.2-1.7.4.162

**Comment by alcatrazEscapee** [comment]
Two things:
- Ingots placed in an anvil will auto select a plan if there's only one available which attaches special data (to track the forging of that ingot), and
- Ingots can only be placed into an ingot pile if they have no additional data (heat, forging, etc.) of any sort. This is intentional as that data would otherwise be erased.

There *may* still be an issue here, e.g. when you remove items from anvils, they try and clear data if there's nothing significant (e.g. null recipe, zero progress), and so in theory should function normally for ingot piles, which may not be occurring when shift clicking out? Specifics would be appreciated.

**Comment by LordFokas** [comment]
I suggest that ingots with forging in progress get a line on the tooltip saying "Forging in Progress".
Putting such an ingot (or any other item being forged) into a water barrel would then erase all forging data (and therefore the tooltip label as well).

It's not perfect, but I think it's an acceptable compromise.

**Comment by alcatrazEscapee** [comment]
Shouldn't've been closed as the tooltip was added, but the important part of my last comment

> There may still be an issue here, e.g. when you remove items from anvils, they try and clear data if there's nothing significant (e.g. null recipe, zero progress), and so in theory should function normally for ingot piles, which may not be occurring when shift clicking out? Specifics would be appreciated.

seems not to be fixed. The important check being `IForgeable.getSteps().hasWork()`

**Comment by eerussianguy** [comment]
3d730f6
