### ISSUE TITLE
Allowing mob spawning on surface during a Bloodmoon

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1598]
There is no way of allowing mob surface spawning during just a bloodmoon, and no way of forcing the spawn from the other mod.

https://github.com/lumien231/Bloodmoon/blob/8cb71258a00dd6406f69f24113b9df9d233c4cff/src/main/java/lumien/bloodmoon/server/BloodmoonHandler.java#L143

**Meta Info**
 - TFC Version: 1.7.4.162
 - Requires Bloodmoon-1.5.3

**Comment by alcatrazEscapee** [comment]
On TFC's end, you should be able to enable mob spawns above ground. You can also disable spawn protection. With both of those off TFC should not interfere with mob spawning at all and blood moon should be free to do whatever they want.

We are not going to add explicit compatibility with it. If there's an API on our end that would be useful I'm all ears, otherwise this is going to be left for addons.
