### ISSUE TITLE
The time at which a barrel is sealed still resets when broken

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#1729]
This bug has not been fixed

**Comment by Charnuz** [comment]
In the future please fill out the template, but I figured out what you meant hopefully. Able to reproduce this by placing an already sealed barrel and then breaking it, which sets the sealed time to when you broke it instead of when it was originally sealed.

**Comment by Charnuz** [comment]
Looks like this is the cause:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/6a930fa6b1b129ebfb57c5ca9bf5950bd8fdd686/src/main/java/net/dries007/tfc/objects/items/itemblock/ItemBlockBarrel.java#L229-L248
Since `fill()` calls `setFluid()` which always sets the seal tick to the current time, overriding what was just set before the call
