### ISSUE TITLE
Old animal food config file prevents Zebu and other newish animals from familiarizing or eating grain

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#1756]
**To Reproduce**
Have an older TFC install before animal_food_data.json was updated with new animals.
Find Zebu in world. Usually somewhere hot.
Attempt to feed them grain.

Reproduce with:
 - TFC Version: build 176 with old config file
 - JEI and WorldEdit mods were present while testing.

Confirmed that Zebu will eat and familiarize if the new config file is present.

**Comment by Gaelmare** [comment]
I've seen quite a few complaints about Zebu, parrots, grouse etc. not eating.

**Comment by eerussianguy** [comment]
Is there any way to fix this besides autodeleting?

**Comment by alcatrazEscapee** [comment]
Not particularly. Notice our ore gen loading has some differences to the two beneath it
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/0029a016f486f342704a24b6890e2b890f9311e3/src/main/java/net/dries007/tfc/util/json/JsonConfigRegistry.java#L53-L75

And in other news, I am beyond ready for this to die in a fire along with everything else that just fails to be a consideration due to datapacks. But it's not particularly a bug, it's the same issue with ore veins.

**Comment by eerussianguy** [comment]
Seeing as we have a new system for this now and we're not revisiting this issue
