### ISSUE TITLE
Crash after creating a new world

### ISSUE THREAD

**Issue by Voleil** [TerraFirmaCraft/TerraFirmaCraft#1829]
Game crashed with an strange error after creating a new world on the latest alpha
crash log: https://www.toptal.com/developers/hastebin/obirimaqih.yaml

**Comment by alcatrazEscapee** [comment]
Forge managed to, in their infinite wisdom, somehow make a bug fix a breaking change:

https://github.com/MinecraftForge/MinecraftForge/commit/82a7ee1416ae42c81dfa2102b5ef5be5a7f86c05#diff-7c536fa26961ab237e59cb9f7e5c030bdb76ef00bba5a26cd545759efaed98cfR8

Just use Forge <= 37.0.126, there's every likelihood we'll bump to 1.18 rather than bother fixing this on latest Forge.

**Comment by Voleil** [comment]
Thanks alc 👍
