### ISSUE TITLE
When you disable animals becoming old boomers they get Thanos snapped

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#1861]
So I just disabled animals becoming old boomers, but that makes every animal disappear. I'm looking for a solution because animals spawned by eggs will disappear.

**Comment by HatcheryRoosters** [comment]
To replicate, set any animals' Elderly config to 0, and they will disappear instantly

**Comment by ACGaming** [comment]
Can confirm this: https://streamable.com/o605pc
Happens to naturally spawned livestock as well.

**Comment by HatcheryRoosters** [comment]
I want a way they can live forever without turning into old boomers and Thanos eventually killing them

**Comment by ACGaming** [comment]
The cause is that unfamiliarized animals will be removed after 125% of their lifespan. It‘s a bit silly that they still get removed when they can‘t actually get old.

A cheap workaround is to set the elder days to high numbers. Make sure not to get near max int, something like `2147483000` worked for me. This will let animals be adults for over 20.000.000 default ingame years.

**Comment by HatcheryRoosters** [comment]
I just wanted to see the unfamiliarized animals get along with animals from other mods and not worry about vanishing

**Comment by HatcheryRoosters** [comment]
It's a relief to see this is getting a solution

**Comment by eerussianguy** [comment]
24f326103fcdaaf4f0daf266323db62ca391d007
