### ISSUE TITLE
[1.18.2] Rain falls through thatch

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#1971]
in 1.18.2-2.0.25, rain particles visually come through thatch, though it appears they count as cover mechanically (e.g. for firepits).

**Comment by alcatrazEscapee** [comment]
Unfortunately, for now, this is intentional - vanilla uses motion blocking to detect if a block is rained on, thatch is not motion blocking, therefor it permits rain to pass through. So short of two options - either modify the way vanilla handles detecting rain (bad idea), or making thatch motion blocking (not happening), there's not much we can do.

*We were looking into alternatives and some very cheeky behavior that would allow thatch to behave a bit like dripleaf, but unsure if it was viable. So *for now*, working as intended.

**Comment by Alex33212** [comment]
Something just occurred to me: would it be possible to make thatch behave like leaves? Since, in TFC, leaves allow players to pass through like thatch, but (for the most part) block rain and snow.

**Comment by alcatrazEscapee** [comment]
Was actually fixed by 0c84a8221e8f054e17b89eb5b168ce7a4a1bf794
