### ISSUE TITLE
[1.18.2] Loottable for Tables, Tall Plants and Mammals

### ISSUE THREAD

**Issue by MrKRew02** [TerraFirmaCraft/TerraFirmaCraft#2012]
I've found some non-critical issues:
* ~~Wrong loottables for Scribing Tables. It drops lectern instead of itself.~~
* ~~Tall plants destroy anything placed above when snow pile is dug: screenshots [before](https://prnt.sc/9hWCzhVIxPFI) and [after](https://prnt.sc/CU05gWxpjpIO).~~
* It seems neither rain nor icicles fill the barrels.
* ~~Crafting recipes of tfc-wood stuff (workbenches and bookshelves) are overwritten with tagged ones. I can solve that with no-more-recipe-conflict-like mod, but...~~

That one is more important I think:
* If time to give birth comes when chuncks unloaded mammals become forever pregnant (brr, it's nightmare for them I suppose). So, if you travel too much part of your livestock like pigs becomes useless. 
I tried to find entity nbt that connected with pregnancy but it was unsuccessful.

buld 1.18.x-2.0.32-alpha

**Comment by alcatrazEscapee** [comment]
In future, please avoid creating "List of everything I think might be wrong" issues, because they don't help with tracking individual problems. A useful process is:

1. Ask - especially if you are unsure if something is a bug or not. We try and avoid the issue tracker used for generic suggestions / enhancements (i.e. "icicles should fill barrels")
3. Submit one issue for one bug.

**Comment by eerussianguy** [comment]
Not sure about the icicle thing but I added the other issue since that's rather important to test. Come talk in discord if the icicles issue crops up.
