### ISSUE TITLE
[1.18.2] Food Incompability with Survive Mod

### ISSUE THREAD

**Issue by Shorepion** [TerraFirmaCraft/TerraFirmaCraft#2060]
## 1) Mods
TerraFirmaCraft-Forge-1.18.2-2.1.2-beta
Patchouli-1.18.2-71.1
Survive-1.18.2-7.1.1
UnionLib-1.18.2-7.2.0-Forge

MC 1.18.2

Forge 40.1.74
 
## 2) Crashlog
https://pastebin.com/1myA1NkV
 
## 3) Detailed description of the issue
Crashing to desktop when trying to eat (right clicking) any food.

## 4) Is the issue repeatable?
 Yes

**Comment by alcatrazEscapee** [comment]
This seems to be an issue with Survive. We both do the same replacement of the player's food data, however they:

1. Replace the food data entirely, without delegating to the existing food data.
2. Assume blindly that their replacement is the only one, and perform no cast checks to see if it is.

We cannot make their handler not crash - that is an issue on their side. Ultimately this seems like a weird mod to include, because they're both adding almost identical systems on the surface (hunger mechanics, thirst, etc.) and you likely won't be able to get both mod's food systems working together as they're both complete replacements.

There *might* be something we can do about the latter point (i.e. nutrition not functioning at all), but it's highly unlikely and dependent on Survive making something that doesn't crash at all, so for now I'd consider the two mods making incompatible changes to the food systems.
