### ISSUE TITLE
Merging two foods together in crafting table causes duplication (Fast Workbench conflict)

### ISSUE THREAD

**Issue by pehala** [TerraFirmaCraft/TerraFirmaCraft#2187]
You can merge multiple (same) foods using a crafting recipe, however if you collect the output with shift it will output 2x the bigger stack you had not the actual amount it should.

**Comment by alcatrazEscapee** [comment]
Cannot reproduce. Are you using any other mods which might interfere with crafting table operation?

Another user in discord was able to reproduce ([Video](https://www.youtube.com/watch?v=F4_sHug4CNI)) but only with the addition of other mods. As such I'm assuming this is a mod conflict.

**Comment by alcatrazEscapee** [comment]
This is due to a bug in Fast Workbench, which is present in at least 1.18 and 1.19, and affects vanilla recipes. As far as I can see, apart from coremodding the hell out of Fast Workbench we don't have anything here we can do to mark this recipe as special or ignored (as evidenced by the fact Fast Workbench still fails to handle this case in vanilla). And our coremodding would basically be just coremodding out the mod's main feature. So it's much easier just to say "Don't use Fast Workbench".

**Edit:** Fast Workbench seems to have fixed this on their end *and* released a fix for 1.18.2.

See https://github.com/Shadows-of-Fire/FastWorkbench/issues/92

**Comment by Shadows-of-Fire** [comment]
Issue resolved on FB's side
