### ISSUE TITLE
Unable to use stripped logs in Create

### ISSUE THREAD

**Issue by FabioTheTurtle** [TerraFirmaCraft/TerraFirmaCraft#2240]
Create Manual Application does not work on TFC Stripped Logs/Wood as they do not have the `forge:stripped_logs` tag.

**Comment by eerussianguy** [comment]
You would do well to actually understand what tags do before you continue to make reports that contain nonsense. Create does not check that tag *at all*, and forge does not include it as one of their default tags, which suggests it's not commonly used either.

Create uses `minecraft:logs` and checks the wrong method of getting the stripped state (the vanilla one instead of the forge added one) which means it cannot capture our logs properly. I filed this at https://github.com/Creators-of-Create/Create/issues/4041 for you.

**Comment by FabioTheTurtle** [comment]
Your team would do well to be more polite when adressing comments.

I made this comment with the information taken directly from the recipe when opening the Create mod .jar, as it calls for stripped logs directly in its recipe.
![Untitled](https://user-images.githubusercontent.com/118239332/203470488-b435a4fc-f8e1-4137-b4f9-cbe7cae49d7e.png)
If, for whatever reason, that's not actually how it works then I feel like I have benefit of the doubt in this case.
Earlier in my copper issue, I was mistaken, for I had (wrongfully) assumed it would the copper tags and I didn't bother to check; this one I did explicitly to make sure I had this issue correct.

**Comment by eerussianguy** [comment]
OK, you saying manual application was incorrect then. You need to post bug reports that contain the correct information. For example, if a recipe does not work, you should post that recipe. Since you went through the work of checking, it is not more work to post the recipe. Otherwise I have to search the create GitHub to find the correct recipe.

**Comment by FabioTheTurtle** [comment]
Aye, I apologise for not posting the recipe in full.

For clarification, this is the Create Manual Application of Andesite Alloys/Copper Ingots/Brass Ingots onto stripped logs (as they share the same basic recipe) to create the relevant casings

**Comment by eerussianguy** [comment]
Added for next version
