### ISSUE TITLE
Bias towards sandy regions in `SoilSurfaceState` is backwards from intent.

### ISSUE THREAD

**Issue by natrow** [TerraFirmaCraft/TerraFirmaCraft#2268]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/9ef7c69750da76c7d11addfe6d1cb6408e664fd2/src/main/java/net/dries007/tfc/world/surface/SoilSurfaceState.java#L101

![2022-12-22_20 47 46](https://user-images.githubusercontent.com/60853993/209257928-3d19b8b3-b271-44bb-8e53-a186b4334653.png)

The transitions actually happen at:
35/36mm Sand
91/92mm Sand / Sandy Loam
146/147mm Sandy Loam
202/203mm Sandy Loam / Loam
258/259mm Loam
313/314mm Laom / Silty Loam
369/370mm Silty Loam
425/426mm Silty Loam / Silt
480/481mm Silt

these values are all calculated with the 20mm bias, using the excel equation
```excel
=CEILING.MATH(J19*500/8.99)-20
```

**Comment by natrow** [comment]
This info should probably also be on the player's field-guide

**Comment by alcatrazEscapee** [comment]
The comment is intended behavior. The issue is the incorrect sign on the operation below. However at this point changing it will also constitute a world generation breaking change (as in harsh borders) which is less than optimal, so it might be works-as-not-intended at this point / for a while.

I don't see any real reason this or these values need to be present in the field guide. As per our guideline

> - It SHOULD contain all information that someone would NEED to play TFC, to a reasonable degree of competence.

The exact rainfall thresholds that govern soil transitions (which are intentionally fuzzy and a bit hidden / trying to be blended) don't really fall into that at all.

**Comment by natrow** [comment]
I believe the bias is actually correct, if it were reversed then it would cause the silt-only region never to spawn (unintuitively)

**Comment by alcatrazEscapee** [comment]
No, it is not. I wrote it, I know the intent. The implementation is wrong.
