### ISSUE TITLE
Configurable auto doDaylightCycle

### ISSUE THREAD

**Issue by ymndoseijin** [TerraFirmaCraft/TerraFirmaCraft#2299]
Reading a couple of issues and the Discord, I see it's not something the team wants to add, I'm wondering why that is. The reason I want to do it is because I wanted to have a longer year length and leave the calendar running all the time, seems like I'll either have to patch the mod to do that or add a fake player to be online all the time.

**Comment by alcatrazEscapee** [comment]
Feel free to PR a config option for it. The primary reason we don't is because it by itself, is almost certainly insufficient as a config change to make TFC playable - you'd need to edit pretty much everything to operate on a longer time scale. But if you want to take that upon yourself, by all means, go ahead.

**Comment by alcatrazEscapee** [comment]
1ca1862ecd776017a2049ba4ed41431e4e4495c4
