### ISSUE TITLE
Certain story advancements not loading when Thermal expansion or Comforts installed on server

### ISSUE THREAD

**Issue by Pixel1011** [TerraFirmaCraft/TerraFirmaCraft#2313]
Mod version: 1.18.2-2.2.8
forge server version: 1.18.2-40.2.0

When Thermal expansion or the Comforts mod is installed, many story mode advancements do not load properly as shown, these are the only ones left:
![](https://b1nzy.take-me-to.space/ydvg8O5.png)
server log with thermal installed: https://pastebin.com/QcKDVHfd (line 39 appears to be where advancement loading starts failing)

I only know of these 2 mods that cause it due to playing all the mods gravitas and these were the 2 i managed to figure out were causing it, so im assuming more mods than just these 2 can cause this issue

**Comment by alcatrazEscapee** [comment]
So first off, we actually hit an unrelated error here, but due to a (frankly, poor API) on Forge's part, it ends up swallowing the error, and cascades into other unrelated errors - as you can see here, with advancements. So first, I fix this error. It now crashes. Why?

Because both Comforts, and Thermal Expansion, register item groups and strip the `makeIcon()` method on client using `@OnlyIn(Dist.CLIENT)`. Which is a bug, they shouldn't be doing this, this behavior hasn't been the case since 1.17, and it's on them to fix.

I've filed this with [Comforts](https://github.com/illusivesoulworks/comforts/issues/114), and [Thermal](https://github.com/CoFH/ThermalCore/issues/9).

In the meantime, I can fix TFC to not silently error out in strange ways here... at the cost of making them plainly incompatible... so I guess I'll fix that too, just in case them or any other mod does this stupid thing and we end up getting the short end of the stick.
