### ISSUE TITLE
Support beams do not work

### ISSUE THREAD

**Issue by jagyCZ** [TerraFirmaCraft/TerraFirmaCraft#2338]
As title says, support beams do not work. I have some other mods active, but that should not be a problem, but who knows.
Other mods: tellme, rubidium, patchouli, oculus, journeymap, jei, jade, configured

This is how I place support beams, with blocks always on top (no gaps) and it does not work, my mine always collapses after some digging:
https://dl.dropboxusercontent.com/s/2xfha549howmzbw/javaw_7cQjqI5GQm.jpg

**Comment by alcatrazEscapee** [comment]
Nothing you have said suggests that support beams don't work. It is entirely possible to have support beams placed, in the aforementioned configuration, and yet still experience a cave in due to *other places* not being properly supported.

You would need to demonstrate an actual situation where a collapse can occur where it shouldn't, as this does not. This just demonstrates you are using unsafe mining techniques and/or do not understand specifically how supports work, to which I would suggest reading the documentation on [Support Beams](https://terrafirmacraft.github.io/Field-Guide/en_us/mechanics/support_beams.html) more closely.
