### ISSUE TITLE
nonfunctioning rock layer size data setting?

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2340]
Following the datapack instructions at https://terrafirmacraft.github.io/Documentation/1.18.x/worldgen/dimension
I created this file: https://github.com/Gaelmare/TFCGyresRockLayerSize/blob/master/src/data/minecraft/dimension/overworld.json

When loaded into a new instance and generating two worlds, with and without this datapack file, no changes to rock layer size appeared via Blazemap/Cartography nor from actual inspection of the rock layers in world.

Attached is the vanilla world generation settings export, showing the rock layer size changed. 
[worldgen_settings_export.json.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11010003/worldgen_settings_export.json.txt)

**Comment by alcatrazEscapee** [comment]
Attached is a datapack which works and shows that yes, this is functional, suggesting the issue is not with TFC but is between the keyboard and chair.

![2023-03-18_21 41 17](https://user-images.githubusercontent.com/35673674/226198715-e3657e98-b85b-4778-be3c-4d3461b6de21.png)

Datapack in question: [tfc-rock-layer-size.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11011945/tfc-rock-layer-size.zip)

**Comment by Gaelmare** [comment]
Thank you for testing. PEBKAC indeed apparently.

**Comment by Gaelmare** [comment]
TIL that if you "Re-Create" a world that used a custom datapack, even if that datapack is no longer shown in the datapack list, like you launched Minecraft without the mod containing that datapack, that custom datapack's settings will still apply.

Wack.
