### ISSUE TITLE
Ducks refuse to lay eggs (Conflict with Radium, solvable with user configuration)

### ISSUE THREAD

**Issue by erv123** [TerraFirmaCraft/TerraFirmaCraft#2367]
![image](https://user-images.githubusercontent.com/55497525/233794087-71d915f8-a931-4b58-a87c-9032f40fb78b.png)
these ducks all have eggs and have had them since i got them a while ago but haven't laid a single one, i tried getting new ducks, moving the nest boxes, moving the whole setup and nothing has worked

**Comment by nbalaguer** [comment]
I have the exact same issue. Those ducks have the "has eggs" tag since early winter. Now at late spring, still no eggs to be seen. Repositioning the nest boxes has not worked for me too.

Version is TerraFirmaCraft-Forge-1.18.2-2.2.15.jar

![2023-04-23_18 26 22](https://user-images.githubusercontent.com/3876046/233852031-0e2a1bce-35fa-4e80-bdc5-7de4c65e2339.png)
![2023-04-23_18 26 23](https://user-images.githubusercontent.com/3876046/233852033-e3231d76-2238-4340-abe2-1f601d49288d.png)

**Comment by alcatrazEscapee** [comment]
I've been trying to investigate this for a bit, see nothing obviously wrong with TFC, but it's turning out to be difficult to establish what the problem is. I have not been able to reproduce it with justl TFC yet.

To quote some findings:

- In some cases, breaking and replacing, or moving nest boxes has seemed to (essentially) instantly fix the issue. (In other cases, not)
- In some cases, it has seemed to be a conflict with any of the mods Starlight, Radium, or Fast Chunk Load, insofar as removing those mods in specific situations has fixed the issue.
- *Generally* it seems to be a mob AI / pathfinding issue, where they can't find, or aren't aware of the nest box. Given that we use the same system that vanilla uses for villager AI (i.e. a duck finding a nest box is basically a villager finding a workstation), and that system was... shall we say *finicky* in vanilla... this may also be a cause.

**Further Info**

This seems to be a conflict with some AI optimizations in Radium (Lithium). For said users, adding the following to `./config/radium.properties` seems to resolve these issues.

```
mixin.ai.goal=false
mixin.ai.poi=false
```

Unfortunately Radium doesn't (yet) have a good way for us to disable these optimizations, but that seems to be the conflict in question.

**Comment by Tander** [comment]
For statistics.
Adding this in Radium config on server:
```
mixin.ai.goal=false
mixin.ai.poi=false
```
then restarting server, and breaking and placing back nests solved the issue.
P.S.: Baby quails are cute as hell

**Comment by Romaq** [comment]
Confirmed this fixed our problem running ATFC with TFC v. 2.2.18 (I note a new release as of today). Add the lines suggested by Tander, reboot, break/ replace nests, get run over by ducks having to lay those eggs RIGHT FREAKIN' NOW!
