### ISSUE TITLE
Version Incompatibility.

### ISSUE THREAD

**Issue by Aculoss** [TerraFirmaCraft/TerraFirmaCraft#2381]
I had both 2.2.16 on client and server, but said server has 2.2.15 and i have 2.2.16. So updated both ends to 2.2.18 and it still happening.

**Comment by alcatrazEscapee** [comment]
Would need logs from both client and server to have a hope of diagnosing what is wrong with your setup.

**Comment by Aculoss** [comment]
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11365448/latest.log)

Server log

**Comment by Aculoss** [comment]
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11365453/latest.log)

Client log

**Comment by alcatrazEscapee** [comment]
You're trying to connect to `autotfc.apexmc.co`, I don't think that's your server. As this looks like a support request, rather than an issue, I would direct you to either the ATFC discord (for help with the modpack) or the TFC discord (for help with TFC specifically). Since we try to use the issue tracker for issues with TFC specifically.
