### ISSUE TITLE
Glowing arrows show up / behave as normal arrows

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2388]
![2023-05-06_23 47 12](https://user-images.githubusercontent.com/52297970/236649373-62dad932-d6f8-4840-a0cb-f7d216f33f47.png)

**Comment by alcatrazEscapee** [comment]
Also have a secondhand report that if shot into the ground and picked up, they are normal arrows (not glow arrows).

**Comment by eerussianguy** [comment]
So the arrow stuck in the player is deeply hardcoded into MC (it doesn't even remember the specific projectiles that hit it, just a number). So that part is won't fix. You'll even notice that for vanilla things like tipped arrows.

If you shoot a glow arrow it gets stuck in the wall and behaves/renders correctly. So that part is fine.

Lastly, I guess people want to be able to pick back up the glow arrows. I'm going to leave this out for now while we think of the potential implications for light sources.

**Comment by muzikbike** [comment]
There is actually a Fabric mod that fixes this if someone wants to have a go at implementing something similar here: https://github.com/mrsterner/BetterStuckArrows

If vanilla can track bee stings separately from arrows, then surely TFC can track normal arrows and glow arrows separately?
