### ISSUE TITLE
`ItemBlockRenderTypes#setRenderLayer` should be replaced by `"render_type"` specified in the block model jsons

### ISSUE THREAD

**Issue by HermitOwO** [TerraFirmaCraft/TerraFirmaCraft#2553]

**Comment by alcatrazEscapee** [comment]
No. This is busywork, in-code registration is not going away in the near future as per the most recent Forge RFC, it creates issues with resource packs that don't include render types (because there's no default), it's a step in the wrong direction for future multiplatform support, and there's literally zero benefit to doing so.
