### ISSUE TITLE
Tameable animals can't spawn (in forge version >=47.1.6)

### ISSUE THREAD

**Issue by TheNameSimonWasAlreadyTaken** [TerraFirmaCraft/TerraFirmaCraft#2556]
Tameable animals don't spawn either naturally, via the summon command or via spawn eggs in forge version 47.1.30. Notably it seems this issue does not occur in a dev environment. Here's a log:

https://pastebin.com/ztBZikuh

**Comment by alcatrazEscapee** [comment]
So ultimately this occurs due to Forge's changes regarding `EntitySizeEvent`. There's not a lot we can do about this short of making some significant changes, and this is also in the window where Lex Forge is known to be fairly broken.

> 47.1.6  Fix entity size event not being fired, changed it to split eye height and size calculations. (#9535) is the version and change log that breaks animal spawning/summoning

@Notenoughmail had nailed down the exact maximum supported version in discord.
