### ISSUE TITLE
It may be incompatible with another mod [Harvest with ease]

### ISSUE THREAD

**Issue by Tollainmear** [TerraFirmaCraft/TerraFirmaCraft#2577]
I encountered this issue in both the 1.18.2 and 1.20.1.

 Before I post issue here, I tried contacting the developer of mod Harvest with ease, after their patient analysis, their suggestion was to try and resolve this issue by contacting the developer of the TFC mod. 

I'm not a modder, so I'm not sure if the solution given by Nyphet aligns with the development strategy of both mods. Therefore, could you please evaluate it? Thank you.

original issue in HWE:
https://github.com/Nyphet/harvest-with-ease/issues/31

And the Nyphet's suggestion:
```
Most likely you need to open an issue with TFC and ask of them to add compatibility with HWE by using the provided API (I think they need to be using the [AfterHarvest event](https://github.com/Nyphet/harvest-with-ease/wiki/Forge-API#afterharvest-event) and reset other properties other than the age).
```

**Comment by alcatrazEscapee** [comment]
Answered in the other issue, in short: We're not adding a dependency on them and implementing their API, because their mod is broken in all number of respects. It would be easier for us to just add right-click harvest to TFC crops than have to hack around their API and terrible assumptions. If I can figure out how without introducing a build time dep, I'll deny this mod from doing anything (and thus breaking shit) in TFC.
