### ISSUE TITLE
There should be a config so we can disable parts of the mod we don't like

### ISSUE THREAD

**Issue by AdvancedGun** [TerraFirmaCraft/TerraFirmaCraft#2643]
Trying to go into the nether but am unable to make a nether portal

**Comment by alcatrazEscapee** [comment]
There literally is a config for that, for the love of god. `enableNetherPortals` in the server config. Otherwise "I should be able to pick exactly the parts of this mod I like and don't like" is a vague and nonsense issue report. If you have _specific suggestions_ for things that you want configurable, or things that you don't already know are configurable, please see the `#suggestions` channel on our discord.

**Comment by MrHiTech123** [comment]
Here's a Reddit thread explaining how to access the server config, if you need
https://www.reddit.com/r/TerraFirmaCraft/comments/zsytaf/any_way_to_change_hostile_mob_spawning_in_118/kjkdrrq/?context=8&depth=9
