### ISSUE TITLE
Support for NBT Tools

### ISSUE THREAD

**Issue by AngellusMortis** [TerraFirmaCraft/TerraFirmaCraft#2658]
It is hard to integrate TFC into other mods that use NBT tools (such as Tetra, Slient Gear and Tinker's Construct) since TFC heavily depends on item tags for tools. 

It would be great if there was some method to extend TFC with datapack allow things like tree feeling, the anvil, and scraping with NBT tools.

**Comment by LordFokas** [comment]
I just want to point out that ItemStack NBT is going away in 1.21 (it has been removed in 1.20.5 already) so this may need to be reviewed. ( source: https://neoforged.net/news/20.5release/ )

Since the other modders are going to have to adapt to this change in the future, I'd recommend either waiting to see what happens before making a decision or taking the chance to "sit everyone" in a chat and agree on a standard.

**Comment by alcatrazEscapee** [comment]
@AngellusMortis does Tetra, Silent Gear, and/or Tinkers Construct provide `Ingredients`, or are their tools identifiable with existing ingredients? (i.e. I'm proposing a switch from a tag to a data-driven arbitrary ingredient.)

**Comment by alcatrazEscapee** [comment]
Also, it would be helpful to get a list of what actions are desirable to expose as "tools", because a lot of TFC internals just use, i.e. `#tfc:hammers` but that influences multiple actions.

**Comment by alcatrazEscapee** [comment]
See #2727 for reasoning + lack of overall response
