### ISSUE TITLE
After right clicking on the chest, the client-side items will become empty

### ISSUE THREAD

**Issue by StrangeSmell** [TerraFirmaCraft/TerraFirmaCraft#2721]
TerraFirmaCraft-Forge-1.20.1-3.2.3
I wrote a chest that would render the items inside, but some players reported that they couldn't see the items after right clicking. After investigation, we found that using it with TFC would result in this situation. I've noticed that the items in chest become empty after right clicking. 
https://github.com/StrangeSmell/NoGuiChest/issues/4

**Comment by StrangeSmell** [comment]
I've solved it for now by sending a packet sync after right clicking, but it flickers briefly. I haven't found how TFC is causing this problem and I'm kind of at my wits end.

**Comment by alcatrazEscapee** [comment]
TFC has it's own chests which would be potentially a compatibility issue, but the issue seems to occur just with TFC present and with vanilla chests? In that case I also find that quite strange, we don't make any modifications to the vanilla chest container, gui, or rendering that I could think would cause a conflict.

**Comment by StrangeSmell** [comment]
Sorry, I get it, it was a problem with my mod and now I've fixed it!
