### ISSUE TITLE
Kelp could generate less tall + reach surface less often

### ISSUE THREAD

**Issue by GeorgeBreahna** [TerraFirmaCraft/TerraFirmaCraft#2724]
Vanilla kelp has the same behavior, but as far as I know it doesn't grow/generate up to the top layer of the ocean.

This LOD behavior seems desirable for swamps and such, but obviously not for oceans. The easiest solution seems to make TFC kelp generate and grow similarly to vanilla kelp in oceans, in that it does not reach the top layer. Vanilla kelp growing mechanics from the [wiki](https://minecraft.fandom.com/wiki/Kelp#Growth_mechanics):

> Kelp, when planted, is generated with a randomly chosen age value, which can be checked when pressing F3. The age value of a newly planted kelp plant varies randomly from 0 to 24. Each time the kelp grows in height by one block, the newly generated top of the kelp plant increases its age by 1. When the top block of the kelp plant reaches an age of 25, it stops growing. This means that kelp can naturally grow to a height between 2 (if the first kelp plant had an age of 24) and 26 blocks (if the first kelp plant had an age of 

TFC kelp littering the surface of ocean LODs:

![kelp_LOD](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/73740814/0ecedba0-fc0e-4cbd-a9b5-5d44b9914b3f)
![kelp_distance](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/73740814/9b445b50-0e2b-4ee2-b74a-dc2bf5562d60)

Vanilla kelp only visible very near shore:

![vanilla_kelp_LOD](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/73740814/fc99c1e5-422e-4e56-8490-2312cd5e7436)
![vanilla_kelp_distance](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/73740814/d2861212-d33d-43ce-9a95-cd25d2bdfeaa)

**Comment by alcatrazEscapee** [comment]
TFC has three different variants of kelp with different growing patterns. This isn't really a complaint about distant horizons (and really, if the complaint is "this looks bad in distant horizons" this is _entirely_ not something we care to fix because it's distant horizons making poor choices on how to render things (i.e. see DH also not rendering our leaves on trees in the past, which also looks bad, and no we're not adopting vanilla leaves because of that).

> as far as I know it doesn't grow/generate up to the top layer of the ocean.

There is a different suggestion buried here, which is to see if there is comparable world gen or if this is entirely DH's problem. Starting with verifying the difference in this claim.

**Comment by alcatrazEscapee** [comment]
Vanilla kelp generates using the following procedure, which doesn't exclude generating at the surface:

- Pick a random height in `[1, 10]`
- Generate a pillar of that height, stopping if not placeable, and place the top block with age in `[20, 23]`

From the [Minecraft Wiki](https://minecraft.wiki/w/Kelp), Kelp can generate at y=62, just not as commonly (0.005% of blocks at y=62, vs. 0.164% of blocks at y=61, peaking at ~0.6% of blocks at y=49).

TFC Kelp generates largely the same way, but with a different distribution of height:

- Random height in `[14, 21]`
- Top block's age in `[17, 25]`

In practice TFC kelp generates higher and reaches closer to the surface more commonly
