### ISSUE TITLE
tfc:item_heat tag causing problems with Applied Energistics 2

### ISSUE THREAD

**Issue by adventurerok** [TerraFirmaCraft/TerraFirmaCraft#2783]
I am playing on a modpack which includes TFC and AE2, and we have some issues with some items (particularly ingots and a few other items) not stacking when autocrafting them. (The autocrafted items don't stack with the non autocrafted ones).

The cause seems to be that the non autocrafted items have the NBT tag

{"tfc:item_heat": {heat: 0.0f, ticks: 0L }}

while the autocrafted items (with gregtech machines) do not get this tag.

as confirmed by using the `/data get entity @s SelectedItem` command:

![2024-09-08_19-44](https://github.com/user-attachments/assets/4f8022da-7b51-4f4a-b973-bbc2ae0bceea)

Feels to me like this tag should be removed from items which are not hot?

Minecraft version is 1.20.1. Terrafirmacraft version is 3.2.7

**Comment by alcatrazEscapee** [comment]
The autocrafted items _should_ have this tag, I do not know what gregtech is doing that is preventing them from instantiating and having capabilities. To be clear:

- This tag is not part of the stack tag, this is part of the capability data (which gets managed by Forge, and saved to the stack tag in certain cases such as serialization)
- This tag is indicating that there's a heat capability attached to the item which is attached by TFC on `AttachCapabilitiesEvent`, and should be present on **every** item stack that can be heated.
- The problematic stack is the one that **does not** have this capability information, not the one that does.

In the tfc client config, `enableDebug` can be used to show the capability NBT separately from the stack NBT. Without any further information this seems like gregtech doing something wrong to create these stacks without a capability.

**Comment by alcatrazEscapee** [comment]
Without any further information this isn't solvable on our end, we're doing everything correctly as it seems. See also the linked issue

**Comment by dos54** [comment]
I would like to add some more information here, from what I can gather (Also playing on a modpack which includes the aforementioned mods)

This problem does not seem to be exclusive to GregTech, and from what I can tell appears to be some weird interaction between TFC, AE2(?), and JEI.

From what I can tell the "Cap" (capability) NBT data gets added at some point after the item's creation(?). It is not present when looking at the item in JEI, but appears once the item is added to an inventory or it is held by the cursor. It looks some things, such as shift-clicking recipes using JEI, don't really care about this. That would make sense as I don't think that JEI cares much about an item's NBT data. As such it doesn't cause problems.

However other things do care about NBT data, such as AE2 auto crafting and storage.. When you shift-click a recipe into an AE2 pattern JEI populates the pattern with ghost items that do not carry any of the "Cap" NBT data. When you try auto crafting using a pattern that was populated by JEI with, for example, steel ingots it causes the system to complain about not having any steel ingots because it's expecting ingots without the Cap NBT data, which the ingots in your system most likely have. The same issue happens when auto crafting an item; if your system expects to retrieve an item without the NBT data but somehow gets one with that data then it just assumes it never retrieved the item.

As for the problems with the items not stacking in your AE2 system I think that items are getting put into the system before the Cap NBT tag is attached to the item, causing the issue. This particular problem is really weird because sometimes when I push from a machine directly into the system it DOES have the data, allowing it to stack with the items already present. But sometimes it DOES NOT have the data, which breaks it. This is what I like to call "EXTREMELY ANNOYING." When I was first trying to test this, pushing items directly into the system caused the data not to be applied and taking the crafted items out of the system then putting them back would make them not stack with the items that had been inserted by a machine. After a while it started working correctly though??

**Comment by Pyritie** [comment]
forwarding [this](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/626#issuecomment-2710659853) here since it's relevant:

> After looking around in the source gregtech I found the issue. They implement a custom ItemStackHandler, which does not trigger the forge AttachCapabilitiesEvent when items are extracted. After invoking the event properly, the issue seems to be fixed.

**Comment by dos54** [comment]
A contributor for GTCEu said [here](https://github.com/GregTechCEu/GregTech-Modern/pull/2953) when responding to a pull request that would have fixed the issue:

> This will slow down performance somewhat and is not the right way to do this, nor the actual reason for your issues in TFG (TerraFirmaGreg).
> 
> The main reason is that `ItemStack` capabilites are lazily initialized - they stay unresolved until someone requests them. This leads to your issue where neither GTM nor AE2 particularly care about the stacks's capabilities, so it won't initialize them. You can see that this is the case by looking at the main constructor for `ItemStack`, where the `super` to `CapabilityProvider` is called with `isLazy = true` and how it affects `CapabilityProvider#gatherCapabilities` and `getCapabilities()`.
> 
> Our recipe handling creates new `ItemStacks`, which are lazy. We don't care about the capabilities, so they don't get initialized. (Currently, there _is_ a time when capabilities _do_ get resolved - if an item tries to get inserted into an inventory with existing items, it will call `ItemHandlerHelper.canItemStacksStack`, which resolves the capabilities - but this is per the default implementation of `ItemStackHandler`)
> 
> Then it gets output directly to an ME system. AE2 doesn't care about the unresolved capabilities when turning an `ItemStack` into an `AEKey` (which is how AE tells things apart), so they don't get initialized. You can see `AEItemKey#serializeStackCaps` calls `CapabilityProvider#serializeCaps`, which (unsurprisingly) respects the laziness of the stack. This is why it fixes itself when you take the item out and put it back in - inventory ticks initialize capabilities.
> 
> I also don't understand why you believe that _our_ implementation is the problem when we completely defer to Forge's `ItemStackHandler` class. `CustomItemStackHandler`'s extract/insert methods defer to `ItemStackHandler`'s methods, we don't reimplement them.
> 
> I don't know if there is a real solution to this problem, as going out of our way to _always_ resolve capabilities seems excessive based on how capabilities work.
