### ISSUE TITLE
Improve `PreciseIngredient` to handle heat similarly as food (time independence), and use custom component tooltips for exact requirements.

### ISSUE THREAD

**Issue by SheReyy** [TerraFirmaCraft/TerraFirmaCraft#2792]
MC: 1.20.1
TFC: 3.2.7
Forge: 47.3.0

In previous versions of JEI, recipes that included heatable ingredients displayed the required heat value to complete the recipe. The last version of JEI where the heat value was shown was in JEI version 15.16.2.73. Here’s how the recipes looked:
![Screenshot_1](https://github.com/user-attachments/assets/95fdd205-aa25-4d7f-9aeb-32e4f12d8628)

Starting with JEI 15.17.0.74 to present, (which is JEI 15.19.5.99) the recipes are shown like this:
![image](https://github.com/user-attachments/assets/058762a9-fc6f-4da2-b774-801010a21e7a)

I'm not sure if this is an issue on TFC's end, or if this can solved on TFC's end, but I wanted to point it out. If needed, I'll also make an issue on JEI's tracker.

**Comment by alcatrazEscapee** [comment]
Are you sure this is actually based on JEI version, and not time in world / time since recipe opened / viewed? TFC attempts to display ingredients as heatable, but has no mechanism for persisting that data (heated items cool down, even in JEI). Even a subtle change to the way JEI constructs an index would affect this by constructing stacks at a different "time", relative to the world time.

As for the display, it's just not accurate. It's at best an approximation, that ignores maximum temperature, only can apply a single minimum temperature, and moreover there just, isn't a mechanism for creating stacks with the right display information, specifically for recipe viewers.

That said, there may be an oppourtunity, with fundamental reworks already done, to provide a better solution in 1.21, so I'm going to leave this issue open as a reminder to myself to poke that sometime.

**Comment by SheReyy** [comment]
I'm not sure how to accurately test this. I created a new world for each JEI version tested. With JEI 15.17.0.74, I couldn't even add a heated ingot to the bookmarks list. The item gets added, but the temperature is never displayed. This doesn't happen with JEI 15.16.2.73.

Another thing I noticed is that in JEI 15.16, the temperature for recipes always resets to the minimum requirement (1232 degrees Celsius in my case) whenever the recipe is opened. The temperature of heated items shown in the bookmarks does decrease, as it does in the recipes, but the recipes always reset.
![image](https://github.com/user-attachments/assets/5d4d7475-b18b-442f-a3f2-de798414fbec)


I'm saying this because you mentioned that TFC has no mechanism for persisting that data. Sorry if I misunderstood what you were trying to say 🙈

Edit: Oh, I think I got it now. You meant, TFC has no way of keeping the temperature still, it will always decrease
