### ISSUE TITLE
The spawn is broken

### ISSUE THREAD

**Issue by RedSGued** [TerraFirmaCraft/TerraFirmaCraft#2796]
I put together an assembly of mods based on TFC and mobs will not spawn on my surface from the word at all, I ran about 1000 blocks and did not meet 1 (there are hostile underground ) . Added mobs from other modifications, both neutral and hostile, they also will not spawn only through summoning eggs, maybe there are any settings or tips about this game version 1.20.1

**Comment by alcatrazEscapee** [comment]
Hostile mobs not spawning on the surface is intentional behavior, this can be disabled in the config, via `enableVanillaMonsters` and `enableVanillaMonstersOnSurface`. Non-hostile from other mods may require compatibility, via datapack, added to be able to spawn in TFC's biomes. In future please direct support requests to our discord, not the issue tracker.
