### ISSUE TITLE
Active windmill duplicates placeable item

### ISSUE THREAD

**Issue by HoshinoTented** [TerraFirmaCraft/TerraFirmaCraft#2802]
I was trying to place a gearbox on an active windmill, but the game didn't consume the gearbox in my hand. This bug won't happen
if I have only one gearbox in hand. Instead, it will take the windmill blade from the windmill.
While testing, I found that it duplicates any placeable item, and this bug won't happen if the windmill has maximum windmill blades.

TFC Version: 3.2.7

**Comment by alcatrazEscapee** [comment]
The issue is similar in 1.20 and 1.21, however #2763 reworks this logic already, and does fix this issue. While debugging I also encountered another similar issue that was also resolved. For now in 1.20, right clicking on a windmill will prioritize attempting to add and remove blades, and be consistent in that manner. In 1.21 the open PR should fix this more robustly.
