### ISSUE TITLE
Items do not stack

### ISSUE THREAD

**Issue by GryphonXY** [TerraFirmaCraft/TerraFirmaCraft#2807]
There is a bug that some items do not stack. The bug was noticed with objects: ores, ingots, sheets, some powders, sticks.
I assume that the bug has something to do with the "temperature". All other items that do not interact in any way with the crucible, fire, etc. stack normally.
The bug is fixed only when the item is thrown away and picked up.
Mod version - [1.20.1-3.2.7]
![tes1](https://github.com/user-attachments/assets/93b0c8e4-a3ce-4983-a85a-ee9952e7f848)

**Comment by alcatrazEscapee** [comment]
Please turn on `enableDebug` and advanced tooltips (F3 + H) in the TFC client config and show the result of hovering over two stacks that apparently do not stack. Without any specific information I am suspicious of a mod conflict as we've seen GT before fuckup our heat capabilities, see #2783

**Comment by GryphonXY** [comment]
Here is an example of items that do not stack.
![221s](https://github.com/user-attachments/assets/3275e6a6-246a-4810-b1c5-bc2cc22e275e)

**Comment by alcatrazEscapee** [comment]
This has nothing to do with temperature, as notably the temperature data is identical between the two stacks; something is setting an empty tag and not removing it. If you have a reproduction case that causes this to occur in TFC, or isolated to a specific mod conflict, we can try and look into it, my assumption is that TFC is not the issue here as we don't manipulate the stack tag directly (which is where the discrepancy exists here).

Without any actual reproduction case as to _how_ these stacks were created in the first place, there's nothing we can do here.
