### ISSUE TITLE
Objects on the floor not recognized by Hwyla

### ISSUE THREAD

**Issue by Tr0ll13n** [TerraFirmaCraft/TerraFirmaCraft#283]
Build #45, with Hwyla mod installed.

Objects like sticks, rocks, and nuggets are not recognized by Hwyla while most other TFC blocks are correctly recognized. Hwyla being very useful when you have several mods installed, I thought it could be useful to report this.

**Comment by alcatrazEscapee** [comment]
This is definitely fixed for The One Probe. It may or may not be fixed with other mods - if they are smart enough they should be able to recognize placed items and pit kilns. If not, then this will likely require an addon, as at the current time we aren't interested in hardcoding support for these mods.

**Comment by Tr0ll13n** [comment]
Just tested The One Probe instead of HWYLA. Placed items are recognized as TFC origin, but their description is "tile.tfc.placed-item-flat.name" for all of them.

**Comment by alcatrazEscapee** [comment]
Use 0.18.1.46
