### ISSUE TITLE
Bloomery produces incorrect bloom size

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#325]
Latest version (58)

I put 24 pieces of large hematite into the bloomery with the equivalent amount of charcoal which should give me a bloom 840 units in size, instead I got a bloom 100 units in size.
![2019-08-22_23 47 56](https://user-images.githubusercontent.com/46166245/63562215-4a2f5580-c537-11e9-859d-5f6aa42065cd.png)

**Comment by DisasterMoo** [comment]
More info after a test: This is a visual bug where the tooltip is showing only 100 units when the actual bloom is 840. The problem lies [here](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/13f918fad12cbc75a8da6fcb840406212d885d02/src/main/java/net/dries007/tfc/objects/items/ItemBloom.java#L71). If user works the bloom in anvil it works as inteded (eg: the full refined bloom will show 100 units and a split operation is going to output the 8 stacks of 100 units + a stack containing 40).

Suggestion to fix: Disable smelting of refined blooms and remove the cap or(uglier) add a specific check for blooms in tooltip.

**Comment by alcatrazEscapee** [comment]
Just override `addMetalInfo` in `ItemBloom` and check the actual value. Fix the bug, don't change mechanics.
