### ISSUE TITLE
Pig iron can't be worked into steel in Wrought Iron Anvil

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#333]
High Carbon Steel is registered as `TIER_IV`

Anvil recipe registration is set on the output tier, so even if high carbon steel was right, the next step is gonna fail.

**Comment by GreyMario** [comment]
Ah, but don't forget that that goes counter to the wiki, as does pig iron being a tier 3 metal. Clearly the intended design is to have steel unworkable entirely, because that would provide parity with the wiki. Actual issue is that pig iron should be a tier 4 metal.

_But that's **wrong**, isn't it?_
