### ISSUE TITLE
Worldgen Crash.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#355]
https://pastebin.com/h5vvdrUe

**Comment by alcatrazEscapee** [comment]
This is a re-occurrence of an old bug, see #39
It was temporarily fixed in d3114ec200582a52caa16fe9a9d1f13a46bf325f
That fix was then removed for a better solution in 45e8fb25e08d56b00f00da80649730a1758a036a
Evidently this did not work.

So if you have *any* consistent information on how to reproduce this issue, please provide it. Seed, coordinates, version, anything.

**Comment by alcatrazEscapee** [comment]
Fixed temporarily again by 7f1c8dfe5559d23ecd91f87189c4a6d218ad69c8
This will likely be re-addressed in 1.14, as it's probably not going to get looked at any sooner
