### ISSUE TITLE
Water jug picks up liquid block

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#403]
When right clicking to fill a jug, it picks up the water source like a bucket. Classic behavior was to leave the block there so that jugs could be refilled infinitely from a single source block

**Comment by alcatrazEscapee** [comment]
This is intentional, as otherwise it would allow fluid duplication (since jugs can technically pick up and hold any liquid and transfer them between liquid containers.)

That said, it can do the same check that barrels do for infinite fluids when trying to fill those from a single source block. Although for consistency's sake, I'm not sure if we should bring that back

**Comment by DisasterMoo** [comment]
> That said, it can do the same check that barrels do for infinite fluids when trying to fill those from a single source block.

Want me to do it?

**Comment by alcatrazEscapee** [comment]
Yes, I think so.
