### ISSUE TITLE
Gravity blocks behave inconsistently when falling on blocks they should destroy.

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#419]
Noticed with marble cobble, haven't tested with other physics blocks, occurs when it passes over a ladder, not just when landing on a solid block below it (breaks even if air below the ladder)

**Comment by alcatrazEscapee** [comment]
From testing: happens with all gravity blocks (cobble, dirt, etc.)

Other weird behavior:
 - pops off on a trapdoor on the top or side of a block (even when placed, not falling, on a trapdoor placed on the top of a block)
 - destroys a trapdoor if it's on the bottom face of a block
 - pops off on a door
 - pops off on a piston extension to the side
 - lands on a piston extended upwards
 - doesn't destroy webs, but takes long enough to fall through them that it pops off due to the timer expiring
 - pops of on a fence gate or fence when falling from > 1 block high, but breaks it when placed immediately above
 - pops off on glass panes from any distance
