### ISSUE TITLE
Food rots in JEI overtime

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#421]
**Describe the bug**
1. What did you expect to happen?
Nothing.
2. What actually happened instead (i.e. what was the bug)
Food eventually rots in JEI causing a terrible aesthetic issue.
![image](https://user-images.githubusercontent.com/40124890/64874642-652b4c00-d643-11e9-9dc3-9a9b479bb65d.png)

**To Reproduce**
1. Wait until food can rot, it will display as such in JEI.

**Meta Info**
 - TFC Version: 1.12.2-0.23.2.70

**Comment by alcatrazEscapee** [comment]
Well here's an interesting issue then:
 - JEI assembles it's list of ingredients, recipes, etc. at startup. So that's when the items are created
 - If we find a way to mark these specific stacks as non-decaying, then that will work. Except, then any time you pull a stack from JEI, you will get a non-expiring one, as all it does is perform a simple copy, which is impossible and also against contract to try and modify.

**Comment by alcatrazEscapee** [comment]
This is apparently not fixed as of Pakratt's stream on 9/21/2019
 - Current solution just involves trying to refresh the ingredients at random intervals. Seems like this isn't sufficient, and that a better solution is needed here.

**Comment by alcatrazEscapee** [comment]
JEI should be fixed (for the most part). Creative tabs are fixed, search mode is not (pfft)
