### ISSUE TITLE
Morning glories can spawn on leaves

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#43]
https://i.imgur.com/w70e78v.png

**Comment by Konlii** [comment]
Yeah... they probably should be split off into a separate plant type than the one moss is in

**Comment by alcatrazEscapee** [comment]
![2019-07-14_13 27 54](https://user-images.githubusercontent.com/35673674/61187064-47d60380-a63b-11e9-9242-b93dbde25f66.png)

**Comment by muzikbike** [comment]
Reindeer lichen also spawns on leaves; intentional?

![2019-08-04_22 29 12](https://user-images.githubusercontent.com/52297970/62429614-b5d88c80-b708-11e9-9f0b-4adeb0107cb7.png)
![2019-08-04_22 39 24](https://user-images.githubusercontent.com/52297970/62429615-bd983100-b708-11e9-8121-643891ec1175.png)
![2019-08-04_22 39 24_2](https://user-images.githubusercontent.com/52297970/62429616-bec95e00-b708-11e9-8f1d-c9d9fc4cc834.png)
