### ISSUE TITLE
TFC olive oil fluid name should be 'oliveoil' and not 'olive_oil' to support other mods.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#456]
As far as I can tell, other mods tend to use 'oliveoil' rather than 'olive_oil'

**Comment by DavidTriphon** [comment]
“As far as I can tell”

Could you please list some sources? In how many cases is this true? In how many cases is this false?

**Comment by alcatrazEscapee** [comment]
If there's no other discussion or reason to be had, here's my two cents:
 - TFC works better if other mods fluids don't match up. Forge's stance on fluids means that if another mod registers a fluid slightly differently, we need to use said fluid instead of having our own, which breaks potential additional properties we attach to fluids (i.e. being able to drink them, alcohol effects, etc.
 - Every other fluid in TFC uses `lower_snake_case` as a naming convention, which is the convention that vanilla uses for any registry object names, and thus changing would be breaking convention.
 - This change would also pointless break existing worlds and require a bunch of busywork that accomplishes basically nothing.
