### ISSUE TITLE
TFC alcohols and waters can be bottled into vanilla water.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#471]
**Describe the bug**
1. What did you expect to happen?
Glass bottle to not fill.
2. What actually happened instead (i.e. what was the bug)
Vanilla glass bottles can be filled with liquid:water when clicking any of the TFC water types (limewater, hotwater, saltwater, freshwater), and any of the TFC alcohol types (rum, beer, whiskey, etc...).

**To Reproduce**

1. Click a fluid from TFC with a glass bottle.
2. Scream in horror!

**Meta Info**

 - TFC Version: 1.12.2-0.24.1.78

**Comment by alcatrazEscapee** [comment]
After looking into this, this is caused by the vanilla water bottle just doing a `Material.WATER` check - we'd probably need to registry replace or hook this via right click event (i.e. override default behavior with a custom `IRightClickBlockAction`

**Comment by Lysergid** [comment]
Hi I'd like to work on this. I have few dumb question since I'm new here and maybe missing something. I'm looking into hook approach.

So. InteractionManager.onRightClickItem cancelling events if we have handler for it. Does it mean TFC may discard hooks from other mods for this event, which is not compatibility friendly?
