### ISSUE TITLE
Bug texture

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [TerraFirmaCraft/TerraFirmaCraft#487]
By the way, it looks like a bug: we could not change the gui texture of the TFC oven to 512x

**Comment by alcatrazEscapee** [comment]
TFC doesn't have an oven. What, *specifically* are you referring to. What texture?

**Comment by Envel-Nikita-Gutsenkov** [comment]
Oven or any other tfc item with gui

**Comment by alcatrazEscapee** [comment]
Seeing as I don't understand what the actual issue you think you are seeing is, I'm going to assume you are just suggesting to increase the resolution of all TFC guis. This makes no sense, all TFC's guis are designed with minecraft style in mind. If you want to increase them to 512x512, feel free to make a resource pack. Otherwise unless you can detail a specific issue or something that looks wrong, I'm closing this.
