### ISSUE TITLE
berry bush issues

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#488]
Build #83

-Bushes don't break automatically when the block beneath them is removed
-Bushes can be stacked infinitely, and you can mix types (I have cloudberry bushes stacked on top of Blueberry bushes that are on top of two blackberry bushes)
      *Although iirc there used to be certain bushes that could stack 2 blocks high in 1.7
-Bushes can be placed underwater
-I can't remember the last one :c

**Comment by reddler97** [comment]
I was going to make an issue on this/these myself good thing I checked the open issues, but since I already put in the work heres the screenshots I took in build # 85

floating bushes after breaking the bottom 
![2019-10-15_03 56 57](https://user-images.githubusercontent.com/8678826/66818321-c5433580-ef02-11e9-9853-ed57bbccf55a.png)

stacking issues
![2019-10-15_04 08 03](https://user-images.githubusercontent.com/8678826/66818401-e3a93100-ef02-11e9-8587-07348203a499.png)
![2019-10-15_04 08 19](https://user-images.githubusercontent.com/8678826/66818406-e60b8b00-ef02-11e9-8da2-21978dd9a6e3.png)

snow falls on bushes:
![2019-10-15_03 55 11](https://user-images.githubusercontent.com/8678826/66818467-fcb1e200-ef02-11e9-9ab2-ea90e32b685d.png)

and bushes that don't that normally don't do damage. do damage when occupying the headspace
![2019-10-15_03 59 18](https://user-images.githubusercontent.com/8678826/66818570-223eeb80-ef03-11e9-8ef6-887c8effb11b.png)
![2019-10-15_03 59 25](https://user-images.githubusercontent.com/8678826/66818582-2408af00-ef03-11e9-9547-b8855d39d61a.png)
