### ISSUE TITLE
Crash when using Ex Nihilo Creatio silkworms to infest TFC leaves

### ISSUE THREAD

**Issue by Aiva418** [TerraFirmaCraft/TerraFirmaCraft#504]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

I was playing a modpack called Terrafirmacraft Reloaded 2 (still in development, currently available here: https://github.com/Verph/TerraFirmaCraft-Reloaded-2/releases). I expected to use a silkworm to infest leaves and acquire string, but the game crashed when the infested leaves attempted to spread to TFC leaf blocks. A similar bug occurs when using a silkworm directly on TFC leaves. I believe it has something to do with a "decay property," which the Ex Nihilo Creatio code can't locate in the TFC code.

Crash log: https://paste.dimdev.org/foxodataqu.mccrash
latest.log: https://hastebin.com/ayetulecad.md

This latest.log is actually an abridged version, as the original was inflated with advancement exceptions that were unrelated to any problems I've experienced so far (console spam is a bug for another report).

**To Reproduce**

0. Back up your saves.
1. Install the latest versions of TFC and Ex Nihilo Creatio. (VanillaFix is recommended, but not required)
2. Use a silkworm on vanilla leaves that are adjacent to TFC leaves.
3. Wait for the block to spread the infestation.

**Meta Info**
 - TFC Version: 0.25.2.86
 - Were any other mods included? Can you reproduce it without these other mods?

Other mods were installed (as part of the TFC Reloaded 2 pack) when I originally encountered this error, but the code directly points to a conflict between TFC and Ex Nihilo Creatio. I have reproduced the error with only TFC, Ex Nihilo Creatio, and Forgelin (dependency).

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

Ex Nihilo Creatio (version: 1.12.2-0.4.7.1)
Forgelin (version 1.8.4)

I don't have much experience with reporting issues on GitHub, so please let me know if you need any more information regarding this bug.
Edit: formatting

**Comment by alcatrazEscapee** [comment]
From my brief inspection, this is from ExNihlo assuming that TFC leaves behave the same as vanilla leaves. If we were to solve this on our end, we have two options:
1) Don't subclass `BlockLeaves` as we don't use all the block state properties that vanilla leaves do, or
2) Make TFC leaves behave like vanilla leaves.

Neither of those I particularly want to do. Looking through ExNihlo's source, I believe they already special-case Forestry leaves, so I think since this is due to them assuming something about our leaves, it would be much nicer if they just special case TFC leaves as well.
See https://github.com/BloodyMods/ExNihiloCreatio/issues/279

**Comment by SirLyle** [comment]
The latest release of Ex Nihilo Creatio should address this issue.
