### ISSUE TITLE
Conflict between sword and mace metal content in anvil and mold recipes

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#511]
Swords and maces are listed as containing 200 units of metal, yet only take 100 units in a ceramic mold. The sword recipe on the anvil is also only a single ingot. 

Since metal can be melted down in the forge, this creates metal out of nowhere.

This is a inherent conflict in TFC classic, as the recipes are inconsistent between anvil and mold. Since they can't be melted down, this isn't a problem there.

 - TFC Version: Build 86

**Comment by Claycorp** [comment]
Recipes should match Classic, Double ingots on the mace and sword. Then remove the melting down of tools/heads to match classic.

In regard to what should be melt-able classic only allowed ingots, sheets, unfinished armors, anvils and oil lamps. TNG should match this, if pack makers want to do 1:1 recycle they can. If TNG is going to add all of this recycling it should have losses as it allows for infinite working to level otherwise.

https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Core/ItemHeat.java for melting reference.

**Comment by agilmore2** [comment]
Current build is inconsistent with Classic, as swords take a single ingot. However, Classic has always been inconsistent with itself, as tier I-II metals only take one ingot to make a mace/sword in clay, but two ingots on the anvil, as does all other tool metals. I think tools should be consistent between molds and anvils at 100 units, unless we make mace/sword molds take 200 units?

Agreed that the prospect of recycling materials to gain skills is a change. However, that is often what smiths do IRL. I like the change, with perhaps some lossiness. Damaged tools already show losses fast, so perhaps melting a newly forged tool returns 95% of the metal, and damage decreases yield from there?
