### ISSUE TITLE
breaking a tree with an axe at exactly 0 durability doesn't trigger TFC tree felling mechanics

### ISSUE THREAD

**Issue by ourpar** [TerraFirmaCraft/TerraFirmaCraft#514]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
when breaking a tree with an axe at exactly 1 use left (0 durability), I expect the top-most log to break, like how tree felling usually works.

2. What actually happened instead (i.e. what was the bug)
the log I was chopping at broke, leaving the entire tree above intact

4. If they would help to explain the issue, include screenshots

before breaking the bottom-most log:
![javaw_vObMVPquEx](https://user-images.githubusercontent.com/39307411/67457359-10db9a80-f5f9-11e9-97a1-263875c21d05.png)

after breaking the bottom most log:
![javaw_VWUIFvp5ve](https://user-images.githubusercontent.com/39307411/67457401-294bb500-f5f9-11e9-9d1c-4460d5559676.png)

**To Reproduce**
Attention to detail is important!
1. through whatever means, obtain any type of axe and wear it down until it has exactly 1 use (0 durability) remaining. (for testing purposes I used `/give @p tfc:stone/axe/metamorphic 1 55`)
2. chop down any type of tree (not including fruit trees)
3. experience bug

**Meta Info**
 - TFC Version: 0.25.2.86
 - Were any other mods included? Can you reproduce it without these other mods?
only a few clientside mods, still reproducible with only TFC installed

**Comment by alcatrazEscapee** [comment]
This is due to minecraft's order of block breaking logic - the tool is broken first, then the method we are using to break the trees is called after. We can't hook the earlier block breaking methods, as they don't have the required context in order to trigger the tree breaking.

On the bright side, I had this exact same issue with NTP (and fixed it), and we'll very likely adopt that same fix. (see https://github.com/alcatrazEscapee/no-tree-punching/issues/26)

**Comment by alcatrazEscapee** [comment]
#756
