### ISSUE TITLE
JEI doesn't display what items can be melted to produce molten metal.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#535]
That's it really, JEI doesn't display that you can melt things like copper ingots, doubling ingots, sheets etc. Now while it's self explanatory, adding custom entries using CraftTweaker can get confusing when there is no visual for a player to know what can and can't melt.

**Comment by alcatrazEscapee** [comment]
We considered this, but the practicality of it is since metal melting is not special cased for every individual item (thus allowing adding arbitrary metal items via craft tweaker), there isn't a condition we can put that will show up in JEI (i.e. we can't statically assert that during initialization)

However, there is already a tooltip on the item which should show exactly this information - what metal and unit amount.

**Comment by DisasterMoo** [comment]
So, when I were writing JEI and CT compatibility, at first I've added a "Metal Heating" category to show which item melts to X Metal. Of course i hadn't added the amounts (because of the reasons described above), just which metal you get melting a couple of items. Here's the a screenshot of what i did then:
![unknown](https://user-images.githubusercontent.com/22617477/68890044-e1eaad00-06fc-11ea-8758-0f889b5e6502.png)

I can't remember exactly why we removed it (i think we wanted to make integrations with pachoulli and some sort of learning mini-game for that), but surely it is easy to add it.

**Comment by alcatrazEscapee** [comment]
Because the implementation of this was only specific to hardcoded items - the only way we are able to check a metal is at runtime, since it's specific to a capability attaching.

**Comment by DisasterMoo** [comment]
> the only way we are able to check a metal is at runtime

True, but past post-initialization CT isn't allowed to run scripts anymore, which means that items that melt directly to metal would not change anymore, so, i *think* i might have a solution, if that category is desired: store a map of `Metal` -> `List<ItemStack>` loaded only if JEI is present at post-initialization. Search all items once and save it for the category.
