### ISSUE TITLE
small vessels cannot hold various items

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#540]
Small vessels cannot hold light/very small items anymore.
Seeds, feathers, food do not go in.
medium/normal things like nuggets work
light/small things like straw works
medium/very small  things like thatch work.

**Meta Info**
 - TFC Version: build 92

**Comment by DisasterMoo** [comment]
Sorry, I poorly fixed the last issue. Looks like what needs to be done here: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/44acc0182845206ca38d5e4a51a7e38c686475dc/src/main/java/net/dries007/tfc/objects/items/ceramics/ItemSmallVessel.java#L414
should be:
```java
IItemSize cap = CapabilityItemSize.getIItemSize(stack)
if(cap != null)
{
    ...
}
```
@alcatrazEscapee

**Comment by agilmore2** [comment]
Ah, so tfc seeds don't implement IItemSize either, assuming they'd get light/very small by default?

**Comment by alcatrazEscapee** [comment]
TFC items generally implement `IItemSize` as an interface, as it's simpler.
TFC blocks implement the interface, but require `((ItemBlock) stack.getItem()) instanceof IItemSize` to access the interface
Vanilla and other mod items add it as a capability, as we can't implement any interfaces on existing blocks or items.
Thus the reason we have a helper method to get the size from a stack instead of doing `instanceof` directly.
