### ISSUE TITLE
Crucible contents needs a scroll wheel.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#544]
Perhaps add a scroll wheel to the crucible to prevent text rendering issues like so.
Alternatively have text resize itself when more metals are added.
![image](https://user-images.githubusercontent.com/40124890/69094039-8d6e6700-0a47-11ea-9379-fca2043369cb.png)

**Comment by alcatrazEscapee** [comment]
Options I can see:
 - some sort of scrolling (either just scrolling in the area, or a dedicated scroll bar)
 - lowering text size (still has the issue, just less so, will also be increacingly unreadable as minecraft font scales in number of pixels.
 - adding multiple pages. This is the option I think would be the easiest (because this is quite the edge case), least intrusive, and it matches the other gui that has this problem (skills)

**Comment by alcatrazEscapee** [comment]
Superseded by #620
