### ISSUE TITLE
cobblestone no longer fits in small vessels

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#561]
In classic, cobblestone was heavy/very small, and fit inside small vessels:
![2019-11-19_21 43 34](https://user-images.githubusercontent.com/6852298/69213460-66846380-0b21-11ea-807c-87da78a9f850.png)

In TNG, cobblestone does not fit in small vessels, and is also heavy/very small.

**Meta Info**
 - TFC Version: build 94

**Comment by agilmore2** [comment]
![2019-11-19_23 11 22](https://user-images.githubusercontent.com/6852298/69213679-03df9780-0b22-11ea-8f8a-ff5120aa1c75.png)

**Comment by alcatrazEscapee** [comment]
Vessels are limited by size: < Large and < Heavy. We currently default to very small / heavy for `ItemBlock`s. To keep the same stack size, this would need to change to Small / Normal, here:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/api/capability/size/CapabilityItemSize.java#L129

Any anywhere else that value is hardcoded. Would also need to investigate possible side effects caused by this change (likely none, but possible interaction with other size limited containers)

**Comment by Gaelmare** [comment]
It does seem strange to me that 4 Light/Tiny rocks can make a Heavy/V.Small cobble block, so Small/Normal makes sense for cobble blocks and maybe raw blocks.

**Comment by Gaelmare** [comment]
So this was broken in #519 to make the size annotations match Classic. I think the right answer is Medium/Small to match the 32 stack size of Classic while also allowing carrying them in small vessels.
