### ISSUE TITLE
Minor issue with ore dictionary

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#563]
Looks like there's an inconsistency in ore dictionary for small ores and rich/normal/poor ore samples

see https://github.com/TFC-Metallum/TFC-Metallum/issues/23

**Comment by alcatrazEscapee** [comment]
I don't see the issue here? We have four ore piece types: small, poor, normal, and rich, in increasing size, so we use that as a suffix.

**Comment by DisasterMoo** [comment]
Check limonite / magnetite / hematite. i think we should change all small ores to be `orePigIronSmall` or the the 3 to be `oreLimoniteRich` / `oreMagnetiteRich` / `oreHematiteRich` (same thing for the poor and normal)

**Comment by alcatrazEscapee** [comment]
We had this discussion a while ago. The resolution was to keep the ore dictionary names from the metal, not the ore, and to use the suffix corresponding to the size. So in this case, small ores should be changed to be named of the metal (`oreIronSmall`) instead of the individual ores (`oreLimoniteSmall`, `oreHematiteSmall`, etc.)
