### ISSUE TITLE
CME on World tick on player join. V97

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#577]
https://pastebin.com/YRsDXTxY
https://pastebin.com/LWq4Pwdg

Could this be a side effect of the issues of V94 and keeping the world?

**Comment by alcatrazEscapee** [comment]
Seems to be the same issue as #547, just in a different location. I have been completely unable to reproduce this in dev whatsoever, so I don't know if it's due to an older world, or something else. Maybe try with a new world and see if the error persists, and if not, then that would seem to be the solution.
