### ISSUE TITLE
Crucible input slot isn't limited to stack size = 1

### ISSUE THREAD

**Issue by AtomicBlastPony** [TerraFirmaCraft/TerraFirmaCraft#590]
**Describe the bug**
Make sure to include:
1. To get a stack of fired fire bricks
2. I only got one, the rest of the stack disappeared

**To Reproduce**
Put more than one unfired fire brick in a crucible, heat it to max temperature and wait.

**Meta Info**
 - TFC Version: 0.26.6.97

**Comment by AtomicBlastPony** [comment]
Isn't it supposed to be unlimited for ore?

**Comment by alcatrazEscapee** [comment]
While that would be nice (it used to be 1, we increased it because it was a pain), it can lead to problems when you deal with capability modifications on items with stack size. (Namely, this, but also duplication issues, because there's absolutely no handling for capabilities with stack size greater than one)

In order to lessen the pain, one thing that could be changed is allowing metal melted in a charcoal forge to empty into a crucible.

**Comment by alcatrazEscapee** [comment]
Fixed in d5e0a9524825090ebc92a3c13a6ad010ce95e070
Also see #620
