### ISSUE TITLE
Game forgets meat is salted after cooking

### ISSUE THREAD

**Issue by ValueTown1** [TerraFirmaCraft/TerraFirmaCraft#670]
I had salted bear meat that was expiration November 1st
After cooking it was no longer marked as salted and had expiration September 1st
It then allowed me to re-salt it but even after all of that it only went to October 1st and November 1st when preserved.

I opened a new world to test this and it appears to be the same no matter which meat.
Raw bear meat unsalted July 2nd
Raw bear meat salted August 3rd
Raw bear meat salted + vessel October 4th
Cooked bear meat unsalted June 8th
Cooked bear meat salted July 7th
Cooked bear meat salted + vessel September 5th

Cooking a salted meat has the same result as cooking an unsalted meat

Also cooking meat seems to drastically reduce how long the food lasts. Is this intended behavior? Previous versions cooking meat made it last long

mods installed:
CodeChicken Lib 1.8.+
FoamFix
Hwyla
I Know What I'm Doing
Inventory Tweaks
JourneyMap
Just Enough Items
Mouse Tweaks
Not Enough Items 1.8.+r	
TerraFirmaCraft-MC1.12.2-0.27.7.107.jar

**Comment by alcatrazEscapee** [comment]
For most mods / devices, this would be expected behavior. There's nothing that links the input item's food traits (read: salted) to the output item, nor are we going to try and enforce that behavior through some sort of general purpose hack.

However, we should be able to solve this for TFC cooking devices in particular.
