### ISSUE TITLE
Rock blending of ores that can't generate in said rock doesn't look right.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#680]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Nothing but aesthetics and not cutting off useful ore veins.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
While it's not very geologically accurate for ores to generate in a rock type they realistically couldn't, it's even less logical to assume ore could never cross into a non native rock type and blend into the rock type at least somewhat. I propose that the ore blocks TFC has for non native rock types would be utilized in these scenarios so as to make ore veins not suddenly halt and become very poor, and to add a very slight realistic aspect to the game, sure the rock isn't a native rock for the ore but I would expect it to allow some ore to cross over.
![image](https://user-images.githubusercontent.com/40124890/71247616-0136b480-2311-11ea-9070-5d9e690fe072.png)
This is what I'm talking about, if possible I would have the ore yield be less common in these crossover veins, but not a sudden nothingness.
![image](https://user-images.githubusercontent.com/40124890/71247696-2cb99f00-2311-11ea-9e1b-ef4ad8c6f69f.png)

**Meta Info**
 - TFC Version: MC1.12.2-0.27.7.107 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
TFC enhancement, though with better config integrations perhaps mod integration?
 - If necessary, what other mods (including versions) would this require?
Nah.

**Comment by alcatrazEscapee** [comment]
This is intentional behavior, and due to the way rock types generate, not something we can do with the current ore generation. The main problem is that an ore vein doesn't know what rock it's generating in, it just queries each individual block, as the rock generation data is not available due the way ores are placed (i.e. how they avoid cascading lag). So there's no middle ground here - either it will place in all rock types, or none.
