### ISSUE TITLE
Saplings not going away when trees grow.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#695]
Cretan trees will not remove the sapling when generating.
This allows the player to break the wood above and within a minute or so the tree will spawn back again. This is the same issue as #389 
![https://i.imgur.com/WDH1Z8E.png](https://i.imgur.com/WDH1Z8E.png)
TFC 107

**Comment by Gaelmare** [comment]
So the fix for #389 was reverted in because saplings disappear even if the tree won't grow. https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/617

The real issue is that the tree generators for Palm and Conifer don't replace the sapling when they do grow. The rest of the tree generators do not have this problem.
