### ISSUE TITLE
Sprinting/breaking/falling particles of TFC grass is biome-tinted

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#710]
When falling on vanilla grass, the produced particles are of raw dirt;
![2019-12-31_01 33 41](https://user-images.githubusercontent.com/52297970/71607014-e6184000-2b6d-11ea-82c7-4817524b1729.png)

However in TFC's case, this dirt is tinted green by biome for some reason.
![2019-12-31_01 33 57](https://user-images.githubusercontent.com/52297970/71607023-f3352f00-2b6d-11ea-8e1c-324b1690820a.png)

**Comment by Claycorp** [comment]
Not sure how that's a bug, You are landing on grass, the texture should match the grass.

If they where green when landing on dirt it would be an issue. Blocks only have one particle they can use for running/landing and such, Breaking has a separate one.

If you change the texture on the bottom of the vanilla grass the particles will match whatever it is. Otherwise you can change them via resource pack by using a modeled block.

**Comment by muzikbike** [comment]
In vanilla it uses the dirt particles and they aren't coloured, so TFC grass should therefore do the same.

**Comment by alcatrazEscapee** [comment]
There's two things here:
 - the particles are actually currently dirt particles that are getting caught up in the grass color tint. (not a bug)
 - TFC grass *should* use grass particle texture instead of the dirt texture as that's the actual texture of the block in most cases. (bug)

**Comment by muzikbike** [comment]
May have resurfaces in the 1.18 builds. Separate report?
![2023-04-15_15 49 54](https://user-images.githubusercontent.com/52297970/232232094-4548554b-ee03-4a67-8f12-508a1eddf380.png)
