### ISSUE TITLE
Raw stone detached does not display breaking particles or play breaking sounds

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#713]
Potentially more of a 1.14 feature given how it reforms the whole block breaking effect rules.

![2019-12-31_01 53 01](https://user-images.githubusercontent.com/52297970/71607371-c6cee200-2b70-11ea-8662-4285bf7e85c1.png)

**Comment by Claycorp** [comment]
Not sure what this issue is trying to change or fix? These are things that should be talked about in the discord.

Blocks that aren't supported turn into an item. It's a block that exists in the world that is then deleted and dropped as an item, Everything related to something breaking a block is skipped as there isn't anything breaking it.

**Comment by alcatrazEscapee** [comment]
Yeah, I'm going to go with a no on this one. For the same reason we don't throw around particles for every broken block via a tree falling down. (see #248.)
