### ISSUE TITLE
Large Vessel close bug

### ISSUE THREAD

**Issue by paferor** [TerraFirmaCraft/TerraFirmaCraft#719]
When i close a large vessel, and quit the game. After return to the game, the icon show the vessel is open and the date of the close disapear. But the vessel still closed.

Before quit the game
![2020-01-01_23 40 51](https://user-images.githubusercontent.com/59422862/71647034-da08bb80-2cf0-11ea-868c-a3fab4e83438.png)
After play again
![2020-01-01_23 41 05](https://user-images.githubusercontent.com/59422862/71647035-da08bb80-2cf0-11ea-95d1-d5fdc18fe695.png)

**Comment by Bunsan** [comment]
Please provide a complete report. Are other mods loaded? Is this consistently reproducible?

**Comment by paferor** [comment]
Is consistently reproducible.
Mods: Better Foliage, Bookshelf, Controlling, CraftTweaker, CreativeCore, Debark, Dynamic Surroundings, FastFurnace, FastWorkbench, FoamFix, ​Game Stages, GraveStone Mod, Hwyla, 	Inventory Tweaks, Just Enough Items (JEI), Just Mob Heads, LittleTiles, Mouse Tweaks, No Recipe Book, OreLib, Placebo, Realistic Item Drops, Shadowfacts' Forgelin, Smooth Font, TFCTech Unofficial, Toast Control, Waila Harvestability, Waila Stages, Xaero's Minimap, Xaero's World Map

**Comment by Gaelmare** [comment]
I can reproduce this with a smaller set of mods:
Ambience, AmbientSounds, BetterFPS, Controlling, DynamicSurroundings, DynSoundHUDS, Farseek, FoamFix, FPS Reducer, JourneyMap, JEI, MouseTweaks, Optifine, OreLib, TFC, VanillaFix, Waila, Waila Harvestability, Waterflasks

The issue is that the GUI shows it open, while the block in-world is closed. The GUI doesn't allow placement of anything into the vessel, so it still is actually closed behind the scenes.
