### ISSUE TITLE
Fire Clay blocks don't exist, unlike Clay Blocks

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#730]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Inconsistency with vanilla clay blocks existing.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
A block, made of fire clay, near identical to the vanilla clay block.

**Meta Info**
 - TFC Version: 1.12.2-0.27.7.107 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by Claycorp** [comment]
What would the purpose of this be?
Storage?
Is there anything they are going to make?

I wouldn't count it as an inconsistency as Classic didn't have this and the vanilla blocks have a use outside of storage.
If it's wanted for something crafting wise it's fairly easy to add with Content Tweaker or any other block creation mod as they don't do anything special. TFC already has support to work into the mod.

**Comment by UnlimatedStone9** [comment]
"I wouldn't count it as an inconsistency as Classic didn't have this"
Inconsistency with Vanilla, and now according to TFC TNG having clay blocks be obtainable, TFC itself.
Storage, decoration, perhaps a TFC-esque way of making Terracotta, instead of using raw clay.
ContentTweaker isn't an excuse for native TFC, merely for modpacks.

**Comment by Claycorp** [comment]
TFC is an overhaul of vanilla, There is no consistency with Vanilla, only within the mod itself.

Terracotta and Fire Brick are not the same. Terracotta _is_ fired clay by definition, There isn't a reason to change that.

Without a use in the core mod there isn't a reason to add a storage block for it. It's used in two things, a crucible and bricks. You make what you need and it's never touched again. Thus use ContentTweaker to make blocks of it if you want blocks of it as there is no use or reason for TFC to add it.

Clay blocks where required for the Terracotta and they already existed. Otherwise blocks of clay wouldn't exist either.

**Comment by UnlimatedStone9** [comment]
Close in favor of #747, which is in relation to #748.
