### ISSUE TITLE
Putting stacked hides into a limewater barrel yields only one hide.

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#760]
See title. Version 111. Likely caused when there's not enough liquid to convert all hides.

**Comment by alcatrazEscapee** [comment]
This is (as far as I can tell), intentional behavior. TFC barrel recipes operate in two camps:
1. Instant recipes (i.e. limewater) require an excess of item ingredient, and
2. Duration recipes (i.e. hides) will operate on the highest multiplier possible, consuming excess ingredients without producing excess product. This happens for both fluids (as barrels can't store more than one fluid), and items (behavior here).
