### ISSUE TITLE
Trees can be grown using bonemeal

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#765]
Trees grow with bonemeal again because _someone_ used a value for debugging and forgot to change it back.

Instead of messing with these values all the time just add a debug config check to things that need debugging, That's what it's there for.

Thanks for coming to my TED Talk.

**Comment by DisasterMoo** [comment]
It was never changed. Fruit Trees' sapling ever since i made then always accepted bone meal. We let it that way because:
- In classic there was no sapling state (as soon as you planted it it grew to first trunk state)
- You can move saplings this way if you planted it in a wrong place, and to match classic you can use a bonemeal to get to the first stage. Although this can be changed for a fertilizer or something to be more believable than "bone dust".

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/bcb3c97fb054a9c719e29823d500d1fb34acb366/src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeSapling.java#L123-L126

**Comment by Claycorp** [comment]
I was looking at the base sapling. Didn't look at fruit trees specifically, That's fine. 
I'll make sure it's added to the diff page on the wiki. Though I feel that if you fuck up you should pay the price 😉
