### ISSUE TITLE
JEI Metals issues.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#778]
- Currently Casting is missing from all the JEI metal recipes.
- Melting recipes should be using the fluids instead of cast ingots.
- Alloys are only looking at ingots and ores not nuggets.
- Unmounted recipes should should show one per metal
- Metal heating should be search able by input and output.

**Comment by alcatrazEscapee** [comment]
Some info about JEI implementations:
 - For molds, we can consider adding an `ISubtypeInterpreter` to have each mold/metal combination.
 - For unmold recipes, see `IModRegistry#handleRecipes`, which we can register a custom recipe wrapper and handler for unmold recipes. This should allow us to show the actual possible metal inputs + outputs of unmold recipes.

For alloy recipe inputs there are two main options:
1) Use the fluid as an ingredient only, or
2) Show every possible item that can be melted into that fluid (cycling)

Metal heating recipes should be more like the "information" tab, where instead of registering a "input -> output" recipe, they simply show information about item, melting temperature, and result metal.

**Comment by DisasterMoo** [comment]
Closed via https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/bd40578060eea74ef990a360b107d01f9d5f3477
