### ISSUE TITLE
Add config to clay rainfall threshold, adjust default to match dry grass threshold

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#779]
Currently clay only has a grass top on it. This makes clay in dry regions stand out like crazy.

This also doesn't match classic so whats the deal with this?

**Comment by alcatrazEscapee** [comment]
The reason is because our dry grass and clay threshold is different. It can probably be changed quite easily by a config value, then adjusting the default to match the dry grass level.
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/f99b747086e72dc1fc8ac701b2ca29fb46eb176f/src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenSoilPits.java#L37
