### ISSUE TITLE
Picking up sticks / world items gives twice the amount if one is already in inventory

### ISSUE THREAD

**Issue by Samotnik** [TerraFirmaCraft/TerraFirmaCraft#82]
Screenshots: https://imgur.com/a/ZXE66Gp **Build 0.5.1**

1. Can't make more than 4 planks, saws doesn't work if they were used before.

2. Some plants are generated in water and they are making air space like sugar cane in past verions of minecraft.

3/4. It's okay if you take one stick from the ground and you don't any in inventory. It's not okay when you have already one stick in inventory and you gather another one - It will be duplicated

**Comment by alcatrazEscapee** [comment]
Tips for bug reporting: If you have three bug reports, make three bug reports, make three issues. It is easier to track that way. Then we can have meaningful titles - "three little bugs" is useless for organization

That said,
1. is already documented in #63 
2. is intentional - those are meant to be water plants. In 1.14 they will become similar to vanilla kelp / seagrass
3. is new to me

**Comment by Red3Tango** [comment]
With more testing, I found out this behavior only happens when you right-click a world item to pop it off the ground. (item spawned as ground clutter, sticks, ore, rocks)

**Comment by Samotnik** [comment]
> Tips for bug reporting: If you have three bug reports, make three bug reports, make three issues. It is easier to track that way. Then we can have meaningful titles - "three little bugs" is useless for organization
> 
> That said,
> 
> 1. is already documented in #63
> 2. is intentional - those are meant to be water plants. In 1.14 they will become similar to vanilla kelp / seagrass
> 3. is new to me

Alright ;) I'll do better organization next time.
