### ISSUE TITLE
trapdoors use plank blocks instead of lumber

### ISSUE THREAD

**Issue by sacalow** [TerraFirmaCraft/TerraFirmaCraft#848]
recipe for trapdoors is made with plank blocks, which adds up to a significant wood sink to make them despite them being much smaller than Doors, which use lumber items instead. this means that to make 2 trapdoors you need 24 lumber, which is a lot.

**Comment by Claycorp** [comment]
Someone was complaining about the fact trapdoors where made with lumber thus it was changed.

So doors and trapdoors cost the same and give the same amount now. I would say they don't do the same thing though and that's why I likely originally made them with lumber.

Perhaps just bumping it up to 4 trap doors instead of 2 would make them more cost effective?
