### ISSUE TITLE
Prospector's Pick gives "Sample of Air" instead of nothing when there's no ore around

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#854]
**Describe the bug**
The prospector's pick gives you a reading of a "sample of air" when you use it and there's not nearby ore vein to detect, instead of telling you that it found nothing.

**To Reproduce**
Use the prospector's pick anywhere in the world where there's no ore veins nearby.

**Meta Info**
 - TFC Version: 0.29.4.119

**Comment by DisasterMoo** [comment]
That is most certainly a ore vein config error (that in this specific case is registering Air blocks as valid ore for a vein). But i made sure that prospector's pick will not return anything in such cases.

**Comment by alcatrazEscapee** [comment]
I can't reproduce with standard vein generation. If this is a config error, then hiding it in the prospectors pick is *not* what we should be doing, rather, it should be sufficiently warned / logged, and rejected beforehand. Or, if it's an intentional configuration (because there's nothing that says "air" is an invalid block state) then it should report exactly this.

In this case, however, I don't see a vein configuration situation that would let this behavior arise. My best guess is that the blockstate in question doesn't admit an item stack, which is what we use to query the name to display. In which case it's a combination of factors: we don't use the best "block -> item" guess method (`getPickBlock`, provided by forge), which we can fix. Or, it's the other mod's fault / vein configuration person's fault for not using a block that can be effectively pro-picked.
