### ISSUE TITLE
Fluids fighting over one block space when flowing onto eachother.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#899]
This one is hard to describe. So have this instead...
![https://i.imgur.com/ujxDWil.gif](https://i.imgur.com/ujxDWil.gif)

The setup is this:
![https://i.imgur.com/eDp5cbE.png](https://i.imgur.com/eDp5cbE.png)
6 block long channel 7th block drops one. End space must be 2 blocks low one high.
 - TFC Version: 120

**Comment by DavidTriphon** [comment]
I'll look into this. I have two guesses:
- The green liquid is flowing left into the red liquid across the top when it shouldn't be and then correctly flowing downwards.
- The green liquid is flowing left into the red liquid at the bottom when it shouldn't be and then replacing the liquid above it when it shouldn't be.

Since the second possibility requires there to be two flaws working in tandem, I think the first is more likely. I will check later during spring break.

**Comment by Claycorp** [comment]
If you block the flow of the green it will do the same thing on the green side instead of the red. Forgot to mention that.
