### ISSUE TITLE
BetterWithMods HCHunger doesn't work with TFC TNG post 1.12.2-29.5.120

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#921]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Food to be edible while HCHunger is enabled and fat to build up, without hunger maxing at 7 points.
2. What actually happened instead (i.e. what was the bug)
Food occasionally becomes inedible at 7 points of food, or can be eaten for no food benefit.

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 1.12.2-29.5.121-1.12.2-29.5.124 (post 1.12.2-29.5.120)
 - Were any other mods included? Can you reproduce it without these other mods?
BetterWithMods
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
BetterWithMods

**Comment by alcatrazEscapee** [comment]
This is what I understand is happening here:
 - BWM internally changes food to be a 0 - 60 scale instead of a 0 - 20 one.
 - They also replace `FoodStats`, and do it in a much less friendly-to-other-possible-replacements way.
 - Our replacement runs second (thank god)
 - We removed a call to `originalStats.addStats()` [here](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/60a058d27865be5f3535c89438e5c209ec44b3d7/src/main/java/net/dries007/tfc/api/capability/food/FoodStatsTFC.java#L73) as we needed more fine grain control over the food / saturation levels, which results in BWM's food stats never getting notified about the changes. Since they also change the scale, this results in 1/3 of the hunger (from BWM's perspective of 20/60 = 7 hunger), while TFC happily reports that we're at 20/20 hunger.
 - I *think* it is possible to re-add this, given that we take into account the difference with which we handle vanilla hunger / saturation. I would also recommend BWM to be less invasive where possible, but it's a moot point as we end up replacing after.

**Comment by UnlimatedStone9** [comment]
Well that sucks. I see why they set it to 60 though, as hunger is changed to fill less of the bar per food. Very messy design.
If anything can be done to fix it I would be very grateful, however it's definitely not TFC's fault, it's BWM's. Maybe a discussion can take place between the BWM developers about this.
