### ISSUE TITLE
Fruit trees should grow even with blocks next to them

### ISSUE THREAD

**Issue by Yahay944** [TerraFirmaCraft/TerraFirmaCraft#924]
Fruit trees don't grow further without all 4 leaves having grown next to the trunk. I think it would be better to ignore blocks next to the tree at least in the early stages of growth. 
We planned out an orchard with torches and planted fruit saplings next to those. They hadn't grown even after a long time and it turns out it was because of the torches. 
Full blocks like dirt blocked growth which is awkward for orchards on inclines and non-solid blocks like torches and sticks/stones lying on the ground also blocked growth. The tree could perhaps even replace things like sticks or stones with a leaf block when growing.

**Meta Info**
 - TFC Version: 1.12.2-0.30.3.124
 - Enchancement for TFC alone?

**Comment by Claycorp** [comment]
The growth blocking is the same as classic IIRC. Leaves where always the priority to grow, if they can't grow then it won't keep growing trunk.

Also trees are 5x5 when fully grown, a 3x3 tree should have plenty of room to grow in any setup that allows the tree to grow correctly.

The leaves already will replace blocks that are replaceable, Grass/Plants/Flowers.
Ground item's aren't limited to just rocks and sticks anymore so they can't be replaced. So that is working as intended.

**Comment by DisasterMoo** [comment]
I agreed to Clay
