### ISSUE TITLE
Sandwich nutrition calculation not consistent

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#945]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Value of all ingredients to add up the same way in final sandwich
2. What actually happened instead (i.e. what was the bug) When you make a sandwich, the final nutrition value is the value of 1 piece of bread + value of each ingredient. For example, 2x 1 grain bread and 2x 1 vegetable give you 2 sandwich with 1 grain 2 vegetable. Why is this not using all the same logic for all ingredients ?
Option 1, make it that the total nutrition value of the ingredients and the two sandwich is the same, so in this example, 2 sandwich with 1 grain 1 vegetable (because the total of the ingredients is 2 grain 2 vegetable, divided by 2 sandwich).
Option 2, make each sandwich have the total value of the ingredients used. In the example, 2 sandwich that have 2 grain 2 vegetable

**To Reproduce**
Attention to detail is important!
1. make a sandwich

**Meta Info**
 - TFC Version: 125

**Comment by alcatrazEscapee** [comment]
This is intentional. Reasoning is that making meals basically gives you a much higher nutrition / hunger (since hunger remains constant), and that stat is what affects how high your nutrition gets (since nutrition is now completely based on your last N food items eaten.

With that in mind:
 - sandwiches are (average of bread) + sum of ingredients.
 - soups and salads have diminishing returns for adding more ingredients (nutrition = sum of all ingredients * multiplier)
