### ISSUE TITLE
Isolated ore blocks should drop themselves

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#965]
Seems a bit out of place that stone blocks drop, but ores don't. This would also provide a way for the blocks to be obtainable in survival.

![2020-04-07_18 46 14](https://user-images.githubusercontent.com/52297970/78702592-be6d0c80-7900-11ea-8fd7-51976d1565e0.png)

**Comment by Claycorp** [comment]
What purpose does this have?
If people want ore blocks why not just add a crafting recipe for one in your pack?

**Comment by alcatrazEscapee** [comment]
While I don't disagree with this on principle, there's actually a bit more of a technical limitation which makes this not worth doing. Since grade is a metadata based property of the ore block, but the item knows nothing about said property, this would always result in obtaining normal ores.

The fix is to either separate grades to their own blocks (which will happen in 1.15+), but this is a needless compatibility change not worth doing in 1.12, *or*, add metadata handling for ore item blocks (also not worth doing, as it gets thrown out in 1.15 anyway.
