### ISSUE TITLE
Can ride horses without a lead/rope

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#983]
Can ride horses without a lead/rope

**Meta Info**
 - TFC Version: 0.X.X.126 on test server

**Comment by p0kes** [comment]
Thought horses had been completed, but seems they aren't right yet, they can also be tamed without any familiarisation.

**Comment by Azaysol** [comment]
not sure how the devs want familiarization and taming to work. but i was not able to ride a horse till after i tamed it. at least not in ver 127, can you verify after updating

**Comment by p0kes** [comment]
Still happens on 128

**Comment by Azaysol** [comment]
did you tame the horse prior with a lead/rope? can confirmed u can tame without familiarization but not sure if that is intended or not

**Comment by p0kes** [comment]
- Many (but not all) horses on the test server can be tamed without familiarisation.
- A saddled horse can be ridden without a rope, which is different to the Classic method whereby the horse had to be roped to you and then mounted.

**Comment by p0kes** [comment]
This is still an issue as of v146 on test server.
Can still ride horses without rope (is this intentional? It's a change from Classic?).
Can still tame and ride unfamiliarized horses.

**Comment by DisasterMoo** [comment]
As discussed in discord, gonna do a few changes:
- Add a new item made from rope which will leash it's head using a custom state instead of using minecraft's
- You can only ride for the taming process if you familiarize horses first, then leash using this new item.

The final mechanic should be: Familiarize -> Leash it's head -> Mount until tame -> Put saddle = Be free to ride and control it.

The new item should resemble this: 
![image](https://user-images.githubusercontent.com/22617477/84905307-e0180c00-b086-11ea-9733-22f3d75883d0.png)

**Comment by p0kes** [comment]
The new system is working really really well, thanks! 
Halter seems very expensive though, especially compared to a saddle or leather tunic. Perhaps just 1 lead and 1 leather?
