### ISSUE TITLE
Food recipes in JEI can use more randomized items.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#998]
Currently food recipes will cycle at the same rate making it look like all the foods in the recipe must be the same. If this could be randomized it would be better so people don't think they need to use 3 of the same.

TFC 128

**Comment by alcatrazEscapee** [comment]
For reference: I would agree that the JEI recipe is not very accurate for this case. *However*, this is expected JEI behavior, not just for this but any recipe which rotates multiple items. i.e. wooden buckets accept any `lumber` (While the JEI recipe isn't showing that for our ingredients - that's on them, not us to fix if it's considered an issue, as we're using vanilla ingredients now.), but the recipe rotation will only show the same type of lumber in sequence.

I'd agree that the sandwhich recipes could use some better documentation or hints, i.e. "you don't need three items", but I don't really think JEI will be good at showing that. So it's probably a first place wiki, second place JEI type thing unfortunately.

That said we can do what we can but I don't think it's an ultimate solution.

**Comment by DisasterMoo** [comment]
Yeah, this is an issue in JEI.
JEI's cycler rotates every input list once per second. If lists are equal (has the exact same ingredients), obviously their rotation will looks the same.

Edit:
I think got a middle grounds. By changing the json of all sandwiches to use 3 separate lists for each food ingredient while also changing the order of ore dicts, I got this:
![image](https://user-images.githubusercontent.com/22617477/80365097-72591c00-885d-11ea-88c4-eb4bb1afd97a.png)
Now this fix half the problem, since if you click to check how to make a sandwich you're gonna see it working. 

The not fixable part is if you right click to check what a food item can craft you're still gonna see all 3 fixed in place: 
![image](https://user-images.githubusercontent.com/22617477/80365304-bb10d500-885d-11ea-82ad-ed427098c399.png)
